/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */
#include "pydoc_macros.h"
#define D(...) DOC(gr, linalg, __VA_ARGS__)
/*
  This file contains placeholders for docstrings for the Python bindings.
  Do not edit this file.

  This file will be automatically generated.
  If you edit this file, your changes will be overwritten.
*/

static const char *__doc_gr_linalg_matrix_elementwise_multiply_sync =
    R"doc()doc";

static const char *
    __doc_gr_linalg_matrix_elementwise_multiply_sync_matrix_elementwise_multiply_sync =
        R"doc()doc";

static const char *__doc_gr_linalg_matrix_elementwise_multiply_sync_make =
    R"doc()doc";