/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(array_slice.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4babd25aa5a13e67ab956c06760cbf19) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/array_slice.h>
// pydoc.h is automatically generated in the build directory
#include <array_slice_pydoc.h>

void bind_array_slice(py::module &m) {

  // First, bind the SliceSpec structure for each precision type
  using SliceSpec_f = gr::linalg::array_slice<float>::SliceSpec;
  using SliceSpec_d = gr::linalg::array_slice<double>::SliceSpec;
  using SliceSpec_cf = gr::linalg::array_slice<std::complex<float>>::SliceSpec;
  using SliceSpec_cd = gr::linalg::array_slice<std::complex<double>>::SliceSpec;

  py::class_<SliceSpec_f>(m, "SliceSpec")
      .def(py::init<int, int, int>(), py::arg("start") = 0,
           py::arg("stop") = -1, py::arg("step") = 1)
      .def_readwrite("start", &SliceSpec_f::start)
      .def_readwrite("stop", &SliceSpec_f::stop)
      .def_readwrite("step", &SliceSpec_f::step);

  py::class_<SliceSpec_d>(m, "SliceSpec_d")
      .def(py::init<int, int, int>(), py::arg("start") = 0,
           py::arg("stop") = -1, py::arg("step") = 1)
      .def_readwrite("start", &SliceSpec_d::start)
      .def_readwrite("stop", &SliceSpec_d::stop)
      .def_readwrite("step", &SliceSpec_d::step);

  py::class_<SliceSpec_cf>(m, "SliceSpec_cf")
      .def(py::init<int, int, int>(), py::arg("start") = 0,
           py::arg("stop") = -1, py::arg("step") = 1)
      .def_readwrite("start", &SliceSpec_cf::start)
      .def_readwrite("stop", &SliceSpec_cf::stop)
      .def_readwrite("step", &SliceSpec_cf::step);

  py::class_<SliceSpec_cd>(m, "SliceSpec_cd")
      .def(py::init<int, int, int>(), py::arg("start") = 0,
           py::arg("stop") = -1, py::arg("step") = 1)
      .def_readwrite("start", &SliceSpec_cd::start)
      .def_readwrite("stop", &SliceSpec_cd::stop)
      .def_readwrite("step", &SliceSpec_cd::step);

  // Bind sync blocks for all precision types
  using array_slice_sync_f = gr::linalg::array_slice_sync<float>;
  using array_slice_sync_d = gr::linalg::array_slice_sync<double>;
  using array_slice_sync_cf = gr::linalg::array_slice_sync<std::complex<float>>;
  using array_slice_sync_cd =
      gr::linalg::array_slice_sync<std::complex<double>>;

  py::class_<array_slice_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<array_slice_sync_f>>(m, "array_slice_sync_f")
      .def_static("make", &array_slice_sync_f::make, py::arg("input_shape"),
                  py::arg("slice_specs"));

  py::class_<array_slice_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<array_slice_sync_d>>(m, "array_slice_sync_d")
      .def_static("make", &array_slice_sync_d::make, py::arg("input_shape"),
                  py::arg("slice_specs"));

  py::class_<array_slice_sync_cf, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<array_slice_sync_cf>>(m, "array_slice_sync_cf")
      .def_static("make", &array_slice_sync_cf::make, py::arg("input_shape"),
                  py::arg("slice_specs"));

  py::class_<array_slice_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<array_slice_sync_cd>>(m, "array_slice_sync_cd")
      .def_static("make", &array_slice_sync_cd::make, py::arg("input_shape"),
                  py::arg("slice_specs"));

  // Bind PDU blocks for all precision types
  using array_slice_pdu_f = gr::linalg::array_slice_pdu<float>;
  using array_slice_pdu_d = gr::linalg::array_slice_pdu<double>;
  using array_slice_pdu_cf = gr::linalg::array_slice_pdu<std::complex<float>>;
  using array_slice_pdu_cd = gr::linalg::array_slice_pdu<std::complex<double>>;

  py::class_<array_slice_pdu_f, gr::basic_block,
             std::shared_ptr<array_slice_pdu_f>>(m, "array_slice_pdu_f")
      .def_static("make", &array_slice_pdu_f::make, py::arg("input_shapes"),
                  py::arg("slice_specs"));

  py::class_<array_slice_pdu_d, gr::basic_block,
             std::shared_ptr<array_slice_pdu_d>>(m, "array_slice_pdu_d")
      .def_static("make", &array_slice_pdu_d::make, py::arg("input_shapes"),
                  py::arg("slice_specs"));

  py::class_<array_slice_pdu_cf, gr::basic_block,
             std::shared_ptr<array_slice_pdu_cf>>(m, "array_slice_pdu_cf")
      .def_static("make", &array_slice_pdu_cf::make, py::arg("input_shapes"),
                  py::arg("slice_specs"));

  py::class_<array_slice_pdu_cd, gr::basic_block,
             std::shared_ptr<array_slice_pdu_cd>>(m, "array_slice_pdu_cd")
      .def_static("make", &array_slice_pdu_cd::make, py::arg("input_shapes"),
                  py::arg("slice_specs"));
}
