/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(decomp_eigen.h) */
/* BINDTOOL_HEADER_FILE_HASH(a73f9ba592c93c8cb8dec336cab29878) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/decomp_eigen.h>
// pydoc.h is automatically generated in the build directory
#include <decomp_eigen_pydoc.h>

void bind_decomp_eigen(py::module &m) {

  using decomp_eigen_sync_f = gr::linalg::decomp_eigen_sync_f;
  using decomp_eigen_sync_d = gr::linalg::decomp_eigen_sync_d;

  py::class_<decomp_eigen_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_eigen_sync_f>>(m, "decomp_eigen_sync_f",
                                                   D(decomp_eigen))

      .def(py::init(&decomp_eigen_sync_f::make), D(decomp_eigen, make));

  py::class_<decomp_eigen_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_eigen_sync_d>>(m, "decomp_eigen_sync_d",
                                                   D(decomp_eigen))

      .def(py::init(&decomp_eigen_sync_d::make), D(decomp_eigen, make));
}
