/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(decomp_schur.h) */
/* BINDTOOL_HEADER_FILE_HASH(00825cca5b5b5bf377bd3b96daf32f30) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/decomp_schur.h>
// Note: pydoc documentation disabled to avoid missing symbol errors

void bind_decomp_schur(py::module &m) {

  using decomp_schur_sync_f = gr::linalg::decomp_schur_sync_f;
  using decomp_schur_sync_d = gr::linalg::decomp_schur_sync_d;
  using decomp_schur_sync_cf = gr::linalg::decomp_schur_sync_cf;
  using decomp_schur_sync_cd = gr::linalg::decomp_schur_sync_cd;

  using decomp_schur_pdu_f = gr::linalg::decomp_schur_pdu_f;
  using decomp_schur_pdu_d = gr::linalg::decomp_schur_pdu_d;
  using decomp_schur_pdu_cf = gr::linalg::decomp_schur_pdu_cf;
  using decomp_schur_pdu_cd = gr::linalg::decomp_schur_pdu_cd;

  // Sync blocks
  py::class_<decomp_schur_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_schur_sync_f>>(m, "decomp_schur_sync_f")
      .def(py::init([](const std::vector<int> &shape, bool compute_u) {
             return decomp_schur_sync_f::make(shape, compute_u, nullptr);
           }),
           py::arg("shape"), py::arg("compute_u") = true)
      .def(py::init(&decomp_schur_sync_f::make), py::arg("shape"),
           py::arg("compute_u"), py::arg("algorithm"), py::arg("options"))
      .def_static("make", &decomp_schur_sync_f::make, py::arg("shape"),
                  py::arg("compute_u") = true, py::arg("algorithm") = nullptr,
                  py::arg("options") = gr::linalg::schur_options{});

  py::class_<decomp_schur_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_schur_sync_d>>(m, "decomp_schur_sync_d")
      .def(py::init([](const std::vector<int> &shape, bool compute_u) {
             return decomp_schur_sync_d::make(shape, compute_u, nullptr);
           }),
           py::arg("shape"), py::arg("compute_u") = true)
      .def(py::init(&decomp_schur_sync_d::make), py::arg("shape"),
           py::arg("compute_u"), py::arg("algorithm"), py::arg("options"))
      .def_static("make", &decomp_schur_sync_d::make, py::arg("shape"),
                  py::arg("compute_u") = true, py::arg("algorithm") = nullptr,
                  py::arg("options") = gr::linalg::schur_options{});

  py::class_<decomp_schur_sync_cf, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_schur_sync_cf>>(m, "decomp_schur_sync_cf")
      .def(py::init([](const std::vector<int> &shape, bool compute_u) {
             return decomp_schur_sync_cf::make(shape, compute_u, nullptr);
           }),
           py::arg("shape"), py::arg("compute_u") = true)
      .def(py::init(&decomp_schur_sync_cf::make), py::arg("shape"),
           py::arg("compute_u"), py::arg("algorithm"), py::arg("options"))
      .def_static("make", &decomp_schur_sync_cf::make, py::arg("shape"),
                  py::arg("compute_u") = true, py::arg("algorithm") = nullptr,
                  py::arg("options") = gr::linalg::schur_options{});

  py::class_<decomp_schur_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_schur_sync_cd>>(m, "decomp_schur_sync_cd")
      .def(py::init([](const std::vector<int> &shape, bool compute_u) {
             return decomp_schur_sync_cd::make(shape, compute_u, nullptr);
           }),
           py::arg("shape"), py::arg("compute_u") = true)
      .def(py::init(&decomp_schur_sync_cd::make), py::arg("shape"),
           py::arg("compute_u"), py::arg("algorithm"), py::arg("options"))
      .def_static("make", &decomp_schur_sync_cd::make, py::arg("shape"),
                  py::arg("compute_u") = true, py::arg("algorithm") = nullptr,
                  py::arg("options") = gr::linalg::schur_options{});

  // PDU blocks
  py::class_<decomp_schur_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<decomp_schur_pdu_f>>(m, "decomp_schur_pdu_f")
      .def_static("make", &decomp_schur_pdu_f::make, py::arg("shape"),
                  py::arg("compute_u") = true, py::arg("algorithm") = nullptr,
                  py::arg("options") = gr::linalg::schur_options{});

  py::class_<decomp_schur_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<decomp_schur_pdu_d>>(m, "decomp_schur_pdu_d")
      .def_static("make", &decomp_schur_pdu_d::make, py::arg("shape"),
                  py::arg("compute_u") = true, py::arg("algorithm") = nullptr,
                  py::arg("options") = gr::linalg::schur_options{});

  py::class_<decomp_schur_pdu_cf, gr::block, gr::basic_block,
             std::shared_ptr<decomp_schur_pdu_cf>>(m, "decomp_schur_pdu_cf")
      .def_static("make", &decomp_schur_pdu_cf::make, py::arg("shape"),
                  py::arg("compute_u") = true, py::arg("algorithm") = nullptr,
                  py::arg("options") = gr::linalg::schur_options{});

  py::class_<decomp_schur_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<decomp_schur_pdu_cd>>(m, "decomp_schur_pdu_cd")
      .def_static("make", &decomp_schur_pdu_cd::make, py::arg("shape"),
                  py::arg("compute_u") = true, py::arg("algorithm") = nullptr,
                  py::arg("options") = gr::linalg::schur_options{});
}
