/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(decomp_cholesky.h) */
/* BINDTOOL_HEADER_FILE_HASH(a144f556bab78df195d7d55e6ba1fe5b) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/decomp_cholesky.h>
// pydoc.h is automatically generated in the build directory
#include <decomp_cholesky_pydoc.h>

void bind_decomp_cholesky(py::module &m) {

  using decomp_cholesky_sync_f = gr::linalg::decomp_cholesky_sync_f;
  using decomp_cholesky_sync_d = gr::linalg::decomp_cholesky_sync_d;

  py::class_<decomp_cholesky_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_cholesky_sync_f>>(
      m, "decomp_cholesky_sync_f", D(decomp_cholesky))

      .def(py::init(&decomp_cholesky_sync_f::make), D(decomp_cholesky, make));

  py::class_<decomp_cholesky_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_cholesky_sync_d>>(
      m, "decomp_cholesky_sync_d", D(decomp_cholesky))

      .def(py::init(&decomp_cholesky_sync_d::make), D(decomp_cholesky, make));
}
