/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(decomp_lu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7dc8265f58b0f3ef0c0f1cdd161a55de) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/decomp_lu.h>
// pydoc.h is automatically generated in the build directory
#include <decomp_lu_pydoc.h>

void bind_decomp_lu(py::module &m) {

  using decomp_lu_sync_f = gr::linalg::decomp_lu_sync_f;
  using decomp_lu_sync_d = gr::linalg::decomp_lu_sync_d;
  using decomp_lu_sync_c = gr::linalg::decomp_lu_sync_c;

  py::class_<decomp_lu_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_lu_sync_f>>(m, "decomp_lu_sync_f",
                                                D(decomp_lu))

      .def(py::init(&decomp_lu_sync_f::make), D(decomp_lu, make));

  py::class_<decomp_lu_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_lu_sync_d>>(m, "decomp_lu_sync_d",
                                                D(decomp_lu))

      .def(py::init(&decomp_lu_sync_d::make), D(decomp_lu, make));

  py::class_<decomp_lu_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_lu_sync_c>>(m, "decomp_lu_sync_c",
                                                D(decomp_lu))

      .def(py::init(&decomp_lu_sync_c::make), D(decomp_lu, make));
}
