/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(decomp_svd.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(07ac705d880c071583b0c8749314290d) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/decomp_svd.h>
// pydoc.h is automatically generated in the build directory
#include <decomp_svd_pydoc.h>

void bind_decomp_svd(py::module &m) {
  using decomp_svd_sync_f = gr::linalg::decomp_svd_sync_f;
  using decomp_svd_sync_d = gr::linalg::decomp_svd_sync_d;

  py::class_<decomp_svd_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_svd_sync_f>>(m, "decomp_svd_sync_f",
                                                 D(decomp_svd))

      .def(py::init([](const std::vector<int> &shape) {
             return decomp_svd_sync_f::make(shape);
           }),
           py::arg("shape"), D(decomp_svd, make))
      .def(py::init(&decomp_svd_sync_f::make), py::arg("shape"),
           py::arg("algorithm"), D(decomp_svd, make));

  py::class_<decomp_svd_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<decomp_svd_sync_d>>(m, "decomp_svd_sync_d",
                                                 D(decomp_svd))

      .def(py::init([](const std::vector<int> &shape) {
             return decomp_svd_sync_d::make(shape);
           }),
           py::arg("shape"), D(decomp_svd, make))
      .def(py::init(&decomp_svd_sync_d::make), py::arg("shape"),
           py::arg("algorithm"), D(decomp_svd, make));
}
