/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(dot_product.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(db0d35f153dd90ee014347ba442228f8) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/dot_product.h>
// pydoc.h is automatically generated in the build directory
#include <dot_product_pydoc.h>

void bind_dot_product(py::module &m) {

  using dot_product_sync_f = gr::linalg::dot_product_sync_f;
  using dot_product_sync_d = gr::linalg::dot_product_sync_d;
  using dot_product_sync_c = gr::linalg::dot_product_sync_c;
  using dot_product_sync_cd = gr::linalg::dot_product_sync_cd;

  py::class_<dot_product_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<dot_product_sync_f>>(m, "dot_product_sync_f",
                                                  D(dot_product))

      .def_static("make", &dot_product_sync_f::make, py::arg("shape_0"),
                  py::arg("shape_1"), D(dot_product, make))

      ;

  py::class_<dot_product_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<dot_product_sync_d>>(m, "dot_product_sync_d",
                                                  D(dot_product))

      .def_static("make", &dot_product_sync_d::make, py::arg("shape_0"),
                  py::arg("shape_1"), D(dot_product, make))

      ;

  py::class_<dot_product_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<dot_product_sync_c>>(m, "dot_product_sync_c",
                                                  D(dot_product))

      .def_static("make", &dot_product_sync_c::make, py::arg("shape_0"),
                  py::arg("shape_1"), D(dot_product, make))

      ;

  py::class_<dot_product_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<dot_product_sync_cd>>(m, "dot_product_sync_cd",
                                                   D(dot_product))

      .def_static("make", &dot_product_sync_cd::make, py::arg("shape_0"),
                  py::arg("shape_1"), D(dot_product, make))

      ;
}
