/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(eye.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(93919c670ed4de5f2d3fc420085f287b) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/eye.h>
// pydoc.h is automatically generated in the build directory
#include <eye_pydoc.h>

void bind_eye(py::module &m) {

  using eye_sync_f = gr::linalg::eye<float>;
  using eye_sync_d = gr::linalg::eye<double>;
  using eye_sync_cf = gr::linalg::eye<std::complex<float>>;
  using eye_sync_cd = gr::linalg::eye<std::complex<double>>;

  py::class_<eye_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<eye_sync_f>>(m, "eye_sync_f", D(eye))

      .def(py::init(&eye_sync_f::make), py::arg("shape"), D(eye, make))
      .def_static("make", &eye_sync_f::make, py::arg("shape"), D(eye, make));

  py::class_<eye_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<eye_sync_d>>(m, "eye_sync_d", D(eye))

      .def(py::init(&eye_sync_d::make), py::arg("shape"), D(eye, make))
      .def_static("make", &eye_sync_d::make, py::arg("shape"), D(eye, make));

  py::class_<eye_sync_cf, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<eye_sync_cf>>(m, "eye_sync_cf", D(eye))

      .def(py::init(&eye_sync_cf::make), py::arg("shape"), D(eye, make))
      .def_static("make", &eye_sync_cf::make, py::arg("shape"), D(eye, make));

  py::class_<eye_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<eye_sync_cd>>(m, "eye_sync_cd", D(eye))

      .def(py::init(&eye_sync_cd::make), py::arg("shape"), D(eye, make))
      .def_static("make", &eye_sync_cd::make, py::arg("shape"), D(eye, make));
}
