/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(linalg_base_const_sync.h) */
/* BINDTOOL_HEADER_FILE_HASH(bccc25cd76a3697a6a10e034d5904230) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/linalg_base_const_sync.h>
// pydoc.h is automatically generated in the build directory
#include <linalg_base_const_sync_pydoc.h>

void bind_linalg_base_const_sync(py::module &m) {

  using linalg_base_const_sync = gr::linalg::linalg_base_const_sync;

  py::class_<linalg_base_const_sync, gr::,
             std::shared_ptr<linalg_base_const_sync>>(
      m, "linalg_base_const_sync", D(linalg_base_const_sync))

      .def(py::init(&linalg_base_const_sync::make),
           D(linalg_base_const_sync, make))

      ;
}
