/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_transpose.h) */
/* BINDTOOL_HEADER_FILE_HASH(892168b3becd861a46fec89117f4cd69) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_transpose.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_transpose_pydoc.h>

void bind_matrix_transpose(py::module &m) {

  using matrix_transpose_sync_f = gr::linalg::matrix_transpose_sync_f;
  using matrix_transpose_sync_d = gr::linalg::matrix_transpose_sync_d;

  py::class_<matrix_transpose_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_transpose_sync_f>>(
      m, "matrix_transpose_sync_f", D(matrix_transpose))

      .def(py::init(&matrix_transpose_sync_f::make), py::arg("shape"),
           D(matrix_transpose, make))
      .def_static("make", &matrix_transpose_sync_f::make, py::arg("shape"),
                  D(matrix_transpose, make));

  py::class_<matrix_transpose_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_transpose_sync_d>>(
      m, "matrix_transpose_sync_d", D(matrix_transpose))

      .def(py::init(&matrix_transpose_sync_d::make), py::arg("shape"),
           D(matrix_transpose, make))
      .def_static("make", &matrix_transpose_sync_d::make, py::arg("shape"),
                  D(matrix_transpose, make));
}
