/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_solve.h) */
/* BINDTOOL_HEADER_FILE_HASH(656e7409a0887647083b3a8e8c0e2821) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_solve.h>
#include <gnuradio/linalg/types.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_solve_pydoc.h>

using namespace gr::linalg;

void bind_matrix_solve(py::module &m) {
  // Bind the solver_method enum using the template-independent approach
  // Note: All template instantiations share the same enum values, so we use
  // float as reference
  py::enum_<::gr::linalg::matrix_solve<float>::solver_method>(m,
                                                              "solver_method")
      .value("AUTO", ::gr::linalg::matrix_solve<float>::solver_method::AUTO)
      .value("LU", ::gr::linalg::matrix_solve<float>::solver_method::LU)
      .value("QR", ::gr::linalg::matrix_solve<float>::solver_method::QR)
      .value("SVD", ::gr::linalg::matrix_solve<float>::solver_method::SVD)
      .value("CHOLESKY",
             ::gr::linalg::matrix_solve<float>::solver_method::CHOLESKY)
      .export_values();

  // Also bind template-specific enum aliases for compatibility
  py::enum_<::gr::linalg::matrix_solve<double>::solver_method>(
      m, "solver_method_d")
      .value("AUTO", ::gr::linalg::matrix_solve<double>::solver_method::AUTO)
      .value("LU", ::gr::linalg::matrix_solve<double>::solver_method::LU)
      .value("QR", ::gr::linalg::matrix_solve<double>::solver_method::QR)
      .value("SVD", ::gr::linalg::matrix_solve<double>::solver_method::SVD)
      .value("CHOLESKY",
             ::gr::linalg::matrix_solve<double>::solver_method::CHOLESKY)
      .export_values();

  py::enum_<::gr::linalg::matrix_solve<std::complex<float>>::solver_method>(
      m, "solver_method_c")
      .value(
          "AUTO",
          ::gr::linalg::matrix_solve<std::complex<float>>::solver_method::AUTO)
      .value("LU",
             ::gr::linalg::matrix_solve<std::complex<float>>::solver_method::LU)
      .value("QR",
             ::gr::linalg::matrix_solve<std::complex<float>>::solver_method::QR)
      .value(
          "SVD",
          ::gr::linalg::matrix_solve<std::complex<float>>::solver_method::SVD)
      .value("CHOLESKY", ::gr::linalg::matrix_solve<
                             std::complex<float>>::solver_method::CHOLESKY)
      .export_values();

  py::enum_<::gr::linalg::matrix_solve<std::complex<double>>::solver_method>(
      m, "solver_method_cd")
      .value(
          "AUTO",
          ::gr::linalg::matrix_solve<std::complex<double>>::solver_method::AUTO)
      .value(
          "LU",
          ::gr::linalg::matrix_solve<std::complex<double>>::solver_method::LU)
      .value(
          "QR",
          ::gr::linalg::matrix_solve<std::complex<double>>::solver_method::QR)
      .value(
          "SVD",
          ::gr::linalg::matrix_solve<std::complex<double>>::solver_method::SVD)
      .value("CHOLESKY", ::gr::linalg::matrix_solve<
                             std::complex<double>>::solver_method::CHOLESKY)
      .export_values();

  using matrix_solve_sync_f = ::gr::linalg::matrix_solve_sync<float>;
  py::class_<matrix_solve_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_solve_sync_f>>(m, "matrix_solve_sync_f",
                                                   D(matrix_solve_sync))
      .def_static("make", &matrix_solve_sync_f::make, py::arg("shape_a"),
                  py::arg("shape_b"), py::arg("method"), py::arg("tolerance"),
                  D(matrix_solve_sync, make));

  using matrix_solve_sync_d = ::gr::linalg::matrix_solve_sync<double>;
  py::class_<matrix_solve_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_solve_sync_d>>(m, "matrix_solve_sync_d",
                                                   D(matrix_solve_sync))
      .def_static("make", &matrix_solve_sync_d::make, py::arg("shape_a"),
                  py::arg("shape_b"), py::arg("method"), py::arg("tolerance"),
                  D(matrix_solve_sync, make));

  using matrix_solve_sync_c =
      ::gr::linalg::matrix_solve_sync<std::complex<float>>;
  py::class_<matrix_solve_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_solve_sync_c>>(m, "matrix_solve_sync_c",
                                                   D(matrix_solve_sync))
      .def_static("make", &matrix_solve_sync_c::make, py::arg("shape_a"),
                  py::arg("shape_b"), py::arg("method"), py::arg("tolerance"),
                  D(matrix_solve_sync, make));

  using matrix_solve_sync_cd =
      ::gr::linalg::matrix_solve_sync<std::complex<double>>;
  py::class_<matrix_solve_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_solve_sync_cd>>(m, "matrix_solve_sync_cd",
                                                    D(matrix_solve_sync))
      .def_static("make", &matrix_solve_sync_cd::make, py::arg("shape_a"),
                  py::arg("shape_b"), py::arg("method"), py::arg("tolerance"),
                  D(matrix_solve_sync, make));
}