/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_exp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(97ff8a0180031f0924afea89c7227e8f) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_exp.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_exp_pydoc.h>

void bind_matrix_exp(py::module &m) {

  using matrix_exp_sync_f = gr::linalg::matrix_exp_sync<float>;
  using matrix_exp_sync_d = gr::linalg::matrix_exp_sync<double>;
  using matrix_exp_sync_c = gr::linalg::matrix_exp_sync<std::complex<float>>;
  using matrix_exp_sync_cd = gr::linalg::matrix_exp_sync<std::complex<double>>;

  using matrix_exp_pdu_f = gr::linalg::matrix_exp_pdu<float>;
  using matrix_exp_pdu_d = gr::linalg::matrix_exp_pdu<double>;
  using matrix_exp_pdu_c = gr::linalg::matrix_exp_pdu<std::complex<float>>;
  using matrix_exp_pdu_cd = gr::linalg::matrix_exp_pdu<std::complex<double>>;

  // Sync blocks
  py::class_<matrix_exp_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_exp_sync_f>>(m, "matrix_exp_sync_f")

      .def_static("make", &matrix_exp_sync_f::make, py::arg("input_shapes"),
                  py::arg("use_scaling_squaring") = true);

  py::class_<matrix_exp_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_exp_sync_d>>(m, "matrix_exp_sync_d")

      .def_static("make", &matrix_exp_sync_d::make, py::arg("input_shapes"),
                  py::arg("use_scaling_squaring") = true);

  py::class_<matrix_exp_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_exp_sync_c>>(m, "matrix_exp_sync_c")

      .def_static("make", &matrix_exp_sync_c::make, py::arg("input_shapes"),
                  py::arg("use_scaling_squaring") = true);

  py::class_<matrix_exp_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_exp_sync_cd>>(m, "matrix_exp_sync_cd")

      .def_static("make", &matrix_exp_sync_cd::make, py::arg("input_shapes"),
                  py::arg("use_scaling_squaring") = true);

  // PDU blocks
  py::class_<matrix_exp_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_exp_pdu_f>>(m, "matrix_exp_pdu_f")

      .def_static("make", &matrix_exp_pdu_f::make, py::arg("input_shapes"),
                  py::arg("use_scaling_squaring") = true);

  py::class_<matrix_exp_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_exp_pdu_d>>(m, "matrix_exp_pdu_d")

      .def_static("make", &matrix_exp_pdu_d::make, py::arg("input_shapes"),
                  py::arg("use_scaling_squaring") = true);

  py::class_<matrix_exp_pdu_c, gr::block, gr::basic_block,
             std::shared_ptr<matrix_exp_pdu_c>>(m, "matrix_exp_pdu_c")

      .def_static("make", &matrix_exp_pdu_c::make, py::arg("input_shapes"),
                  py::arg("use_scaling_squaring") = true);

  py::class_<matrix_exp_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_exp_pdu_cd>>(m, "matrix_exp_pdu_cd")

      .def_static("make", &matrix_exp_pdu_cd::make, py::arg("input_shapes"),
                  py::arg("use_scaling_squaring") = true);
}
