/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_inverse.h) */
/* BINDTOOL_HEADER_FILE_HASH(bbd31e62611d6b7954afccd4d9c767f1) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_inverse.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_inverse_pydoc.h>

void bind_matrix_inverse(py::module &m) {

  using matrix_inverse_sync_f = gr::linalg::matrix_inverse_sync<float>;
  using matrix_inverse_sync_d = gr::linalg::matrix_inverse_sync<double>;
  using matrix_inverse_sync_c =
      gr::linalg::matrix_inverse_sync<std::complex<float>>;
  using matrix_inverse_sync_cd =
      gr::linalg::matrix_inverse_sync<std::complex<double>>;

  py::class_<matrix_inverse_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_inverse_sync_f>>(m, "matrix_inverse_sync_f",
                                                     D(matrix_inverse))

      .def(py::init(&matrix_inverse_sync_f::make), py::arg("shape"),
           D(matrix_inverse, make))
      .def_static("make", &matrix_inverse_sync_f::make, py::arg("shape"),
                  D(matrix_inverse, make));

  py::class_<matrix_inverse_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_inverse_sync_d>>(m, "matrix_inverse_sync_d",
                                                     D(matrix_inverse))

      .def(py::init(&matrix_inverse_sync_d::make), py::arg("shape"),
           D(matrix_inverse, make))
      .def_static("make", &matrix_inverse_sync_d::make, py::arg("shape"),
                  D(matrix_inverse, make));

  py::class_<matrix_inverse_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_inverse_sync_c>>(m, "matrix_inverse_sync_c",
                                                     D(matrix_inverse))

      .def(py::init(&matrix_inverse_sync_c::make), py::arg("shape"),
           D(matrix_inverse, make))
      .def_static("make", &matrix_inverse_sync_c::make, py::arg("shape"),
                  D(matrix_inverse, make));

  py::class_<matrix_inverse_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_inverse_sync_cd>>(
      m, "matrix_inverse_sync_cd", D(matrix_inverse))

      .def(py::init(&matrix_inverse_sync_cd::make), py::arg("shape"),
           D(matrix_inverse, make))
      .def_static("make", &matrix_inverse_sync_cd::make, py::arg("shape"),
                  D(matrix_inverse, make));
}
