/*
 * Copyright 2025 Wylie Standage-Beier.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_covariance.h) */
/* BINDTOOL_HEADER_FILE_HASH(992d22ee53b7b99eab7e6d92eac7b5ec) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_covariance.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_covariance_pydoc.h>

void bind_matrix_covariance(py::module &m) {

  using matrix_covariance_sync_f = gr::linalg::matrix_covariance_sync_f;
  using matrix_covariance_sync_d = gr::linalg::matrix_covariance_sync_d;
  using matrix_covariance_sync_cf = gr::linalg::matrix_covariance_sync_cf;
  using matrix_covariance_sync_cd = gr::linalg::matrix_covariance_sync_cd;

  using matrix_covariance_pdu_f = gr::linalg::matrix_covariance_pdu_f;
  using matrix_covariance_pdu_d = gr::linalg::matrix_covariance_pdu_d;
  using matrix_covariance_pdu_cf = gr::linalg::matrix_covariance_pdu_cf;
  using matrix_covariance_pdu_cd = gr::linalg::matrix_covariance_pdu_cd;

  // Sync blocks - float
  py::class_<matrix_covariance_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_covariance_sync_f>>(
      m, "matrix_covariance_sync_f", D(matrix_covariance_sync_f))

      .def(py::init(&matrix_covariance_sync_f::make), py::arg("shape"),
           py::arg("unbiased") = true, py::arg("center") = true,
           D(matrix_covariance_sync_f, make))
      .def_static("make", &matrix_covariance_sync_f::make, py::arg("shape"),
                  py::arg("unbiased") = true, py::arg("center") = true,
                  D(matrix_covariance_sync_f, make))
      .def("set_unbiased", &matrix_covariance_sync_f::set_unbiased,
           py::arg("unbiased"), D(matrix_covariance_sync_f, set_unbiased))
      .def("get_unbiased", &matrix_covariance_sync_f::get_unbiased,
           D(matrix_covariance_sync_f, get_unbiased))
      .def("set_center", &matrix_covariance_sync_f::set_center,
           py::arg("center"), D(matrix_covariance_sync_f, set_center))
      .def("get_center", &matrix_covariance_sync_f::get_center,
           D(matrix_covariance_sync_f, get_center));

  // Sync blocks - double
  py::class_<matrix_covariance_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_covariance_sync_d>>(
      m, "matrix_covariance_sync_d", D(matrix_covariance_sync_d))

      .def(py::init(&matrix_covariance_sync_d::make), py::arg("shape"),
           py::arg("unbiased") = true, py::arg("center") = true,
           D(matrix_covariance_sync_d, make))
      .def_static("make", &matrix_covariance_sync_d::make, py::arg("shape"),
                  py::arg("unbiased") = true, py::arg("center") = true,
                  D(matrix_covariance_sync_d, make))
      .def("set_unbiased", &matrix_covariance_sync_d::set_unbiased,
           py::arg("unbiased"), D(matrix_covariance_sync_d, set_unbiased))
      .def("get_unbiased", &matrix_covariance_sync_d::get_unbiased,
           D(matrix_covariance_sync_d, get_unbiased))
      .def("set_center", &matrix_covariance_sync_d::set_center,
           py::arg("center"), D(matrix_covariance_sync_d, set_center))
      .def("get_center", &matrix_covariance_sync_d::get_center,
           D(matrix_covariance_sync_d, get_center));

  // Sync blocks - complex float
  py::class_<matrix_covariance_sync_cf, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_covariance_sync_cf>>(
      m, "matrix_covariance_sync_cf", D(matrix_covariance_sync_cf))

      .def(py::init(&matrix_covariance_sync_cf::make), py::arg("shape"),
           py::arg("unbiased") = true, py::arg("center") = true,
           D(matrix_covariance_sync_cf, make))
      .def_static("make", &matrix_covariance_sync_cf::make, py::arg("shape"),
                  py::arg("unbiased") = true, py::arg("center") = true,
                  D(matrix_covariance_sync_cf, make))
      .def("set_unbiased", &matrix_covariance_sync_cf::set_unbiased,
           py::arg("unbiased"), D(matrix_covariance_sync_cf, set_unbiased))
      .def("get_unbiased", &matrix_covariance_sync_cf::get_unbiased,
           D(matrix_covariance_sync_cf, get_unbiased))
      .def("set_center", &matrix_covariance_sync_cf::set_center,
           py::arg("center"), D(matrix_covariance_sync_cf, set_center))
      .def("get_center", &matrix_covariance_sync_cf::get_center,
           D(matrix_covariance_sync_cf, get_center));

  // Sync blocks - complex double
  py::class_<matrix_covariance_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_covariance_sync_cd>>(
      m, "matrix_covariance_sync_cd", D(matrix_covariance_sync_cd))

      .def(py::init(&matrix_covariance_sync_cd::make), py::arg("shape"),
           py::arg("unbiased") = true, py::arg("center") = true,
           D(matrix_covariance_sync_cd, make))
      .def_static("make", &matrix_covariance_sync_cd::make, py::arg("shape"),
                  py::arg("unbiased") = true, py::arg("center") = true,
                  D(matrix_covariance_sync_cd, make))
      .def("set_unbiased", &matrix_covariance_sync_cd::set_unbiased,
           py::arg("unbiased"), D(matrix_covariance_sync_cd, set_unbiased))
      .def("get_unbiased", &matrix_covariance_sync_cd::get_unbiased,
           D(matrix_covariance_sync_cd, get_unbiased))
      .def("set_center", &matrix_covariance_sync_cd::set_center,
           py::arg("center"), D(matrix_covariance_sync_cd, set_center))
      .def("get_center", &matrix_covariance_sync_cd::get_center,
           D(matrix_covariance_sync_cd, get_center));

  // PDU blocks - float
  py::class_<matrix_covariance_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_covariance_pdu_f>>(
      m, "matrix_covariance_pdu_f", D(matrix_covariance_pdu_f))

      .def(py::init(&matrix_covariance_pdu_f::make), py::arg("shape"),
           py::arg("unbiased") = true, py::arg("center") = true,
           D(matrix_covariance_pdu_f, make))
      .def_static("make", &matrix_covariance_pdu_f::make, py::arg("shape"),
                  py::arg("unbiased") = true, py::arg("center") = true,
                  D(matrix_covariance_pdu_f, make))
      .def("set_unbiased", &matrix_covariance_pdu_f::set_unbiased,
           py::arg("unbiased"), D(matrix_covariance_pdu_f, set_unbiased))
      .def("get_unbiased", &matrix_covariance_pdu_f::get_unbiased,
           D(matrix_covariance_pdu_f, get_unbiased))
      .def("set_center", &matrix_covariance_pdu_f::set_center,
           py::arg("center"), D(matrix_covariance_pdu_f, set_center))
      .def("get_center", &matrix_covariance_pdu_f::get_center,
           D(matrix_covariance_pdu_f, get_center));

  // PDU blocks - double
  py::class_<matrix_covariance_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_covariance_pdu_d>>(
      m, "matrix_covariance_pdu_d", D(matrix_covariance_pdu_d))

      .def(py::init(&matrix_covariance_pdu_d::make), py::arg("shape"),
           py::arg("unbiased") = true, py::arg("center") = true,
           D(matrix_covariance_pdu_d, make))
      .def_static("make", &matrix_covariance_pdu_d::make, py::arg("shape"),
                  py::arg("unbiased") = true, py::arg("center") = true,
                  D(matrix_covariance_pdu_d, make))
      .def("set_unbiased", &matrix_covariance_pdu_d::set_unbiased,
           py::arg("unbiased"), D(matrix_covariance_pdu_d, set_unbiased))
      .def("get_unbiased", &matrix_covariance_pdu_d::get_unbiased,
           D(matrix_covariance_pdu_d, get_unbiased))
      .def("set_center", &matrix_covariance_pdu_d::set_center,
           py::arg("center"), D(matrix_covariance_pdu_d, set_center))
      .def("get_center", &matrix_covariance_pdu_d::get_center,
           D(matrix_covariance_pdu_d, get_center));

  // PDU blocks - complex float
  py::class_<matrix_covariance_pdu_cf, gr::block, gr::basic_block,
             std::shared_ptr<matrix_covariance_pdu_cf>>(
      m, "matrix_covariance_pdu_cf", D(matrix_covariance_pdu_cf))

      .def(py::init(&matrix_covariance_pdu_cf::make), py::arg("shape"),
           py::arg("unbiased") = true, py::arg("center") = true,
           D(matrix_covariance_pdu_cf, make))
      .def_static("make", &matrix_covariance_pdu_cf::make, py::arg("shape"),
                  py::arg("unbiased") = true, py::arg("center") = true,
                  D(matrix_covariance_pdu_cf, make))
      .def("set_unbiased", &matrix_covariance_pdu_cf::set_unbiased,
           py::arg("unbiased"), D(matrix_covariance_pdu_cf, set_unbiased))
      .def("get_unbiased", &matrix_covariance_pdu_cf::get_unbiased,
           D(matrix_covariance_pdu_cf, get_unbiased))
      .def("set_center", &matrix_covariance_pdu_cf::set_center,
           py::arg("center"), D(matrix_covariance_pdu_cf, set_center))
      .def("get_center", &matrix_covariance_pdu_cf::get_center,
           D(matrix_covariance_pdu_cf, get_center));

  // PDU blocks - complex double
  py::class_<matrix_covariance_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_covariance_pdu_cd>>(
      m, "matrix_covariance_pdu_cd", D(matrix_covariance_pdu_cd))

      .def(py::init(&matrix_covariance_pdu_cd::make), py::arg("shape"),
           py::arg("unbiased") = true, py::arg("center") = true,
           D(matrix_covariance_pdu_cd, make))
      .def_static("make", &matrix_covariance_pdu_cd::make, py::arg("shape"),
                  py::arg("unbiased") = true, py::arg("center") = true,
                  D(matrix_covariance_pdu_cd, make))
      .def("set_unbiased", &matrix_covariance_pdu_cd::set_unbiased,
           py::arg("unbiased"), D(matrix_covariance_pdu_cd, set_unbiased))
      .def("get_unbiased", &matrix_covariance_pdu_cd::get_unbiased,
           D(matrix_covariance_pdu_cd, get_unbiased))
      .def("set_center", &matrix_covariance_pdu_cd::set_center,
           py::arg("center"), D(matrix_covariance_pdu_cd, set_center))
      .def("get_center", &matrix_covariance_pdu_cd::get_center,
           D(matrix_covariance_pdu_cd, get_center));
}