/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_reshape.h) */
/* BINDTOOL_HEADER_FILE_HASH(2051c9b2fd5cfcc8b2eb3e13406a0229) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_reshape.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_reshape_pydoc.h>

void bind_matrix_reshape(py::module &m) {
  using matrix_reshape_sync_f = ::gr::linalg::matrix_reshape_sync<float>;
  py::class_<matrix_reshape_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_reshape_sync_f>>(m, "matrix_reshape_sync_f",
                                                     D(matrix_reshape_sync))
      .def_static("make", &matrix_reshape_sync_f::make, py::arg("input_shape"),
                  py::arg("output_shape"), D(matrix_reshape_sync, make));

  using matrix_reshape_sync_d = ::gr::linalg::matrix_reshape_sync<double>;
  py::class_<matrix_reshape_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_reshape_sync_d>>(m, "matrix_reshape_sync_d",
                                                     D(matrix_reshape_sync))
      .def_static("make", &matrix_reshape_sync_d::make, py::arg("input_shape"),
                  py::arg("output_shape"), D(matrix_reshape_sync, make));

  using matrix_reshape_sync_c =
      ::gr::linalg::matrix_reshape_sync<std::complex<float>>;
  py::class_<matrix_reshape_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_reshape_sync_c>>(m, "matrix_reshape_sync_c",
                                                     D(matrix_reshape_sync))
      .def_static("make", &matrix_reshape_sync_c::make, py::arg("input_shape"),
                  py::arg("output_shape"), D(matrix_reshape_sync, make));

  using matrix_reshape_sync_cd =
      ::gr::linalg::matrix_reshape_sync<std::complex<double>>;
  py::class_<matrix_reshape_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_reshape_sync_cd>>(
      m, "matrix_reshape_sync_cd", D(matrix_reshape_sync))
      .def_static("make", &matrix_reshape_sync_cd::make, py::arg("input_shape"),
                  py::arg("output_shape"), D(matrix_reshape_sync, make));
}