/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_add.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6be21a50c62fdad024c80878ce666367) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_add.h>
#include <gnuradio/linalg/types.h>

using namespace gr::linalg;
// pydoc.h is automatically generated in the build directory
#include <matrix_add_pydoc.h>

void bind_matrix_add(py::module &m) {

  using matrix_add_sync_f = gr::linalg::matrix_add_sync_f;
  using matrix_add_sync_d = gr::linalg::matrix_add_sync_d;

  py::class_<matrix_add_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_add_sync_f>>(m, "matrix_add_sync_f",
                                                 D(matrix_add))

      .def(py::init([](const types::shape &shape, int num_inputs = 2) {
             return matrix_add_sync_f::make(shape, num_inputs);
           }),
           py::arg("shape"), py::arg("num_inputs") = 2)
      .def_static(
          "make",
          [](const types::shape &shape, int num_inputs = 2) {
            return matrix_add_sync_f::make(shape, num_inputs);
          },
          py::arg("shape"), py::arg("num_inputs") = 2);

  py::class_<matrix_add_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_add_sync_d>>(m, "matrix_add_sync_d",
                                                 D(matrix_add))

      .def(py::init([](const types::shape &shape, int num_inputs = 2) {
             return matrix_add_sync_d::make(shape, num_inputs);
           }),
           py::arg("shape"), py::arg("num_inputs") = 2)
      .def_static(
          "make",
          [](const types::shape &shape, int num_inputs = 2) {
            return matrix_add_sync_d::make(shape, num_inputs);
          },
          py::arg("shape"), py::arg("num_inputs") = 2);
}
