/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_pseudo_inverse.h) */
/* BINDTOOL_HEADER_FILE_HASH(7d67f4b445979e6c6501ac7ce85dc77d) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_pseudo_inverse.h>
// pydoc.h is automatically generated in the build directory
// #include <matrix_pseudo_inverse_pydoc.h>  // Commented out for now

void bind_matrix_pseudo_inverse(py::module &m) {
  using matrix_pseudo_inverse_sync_f = gr::linalg::matrix_pseudo_inverse_sync_f;
  using matrix_pseudo_inverse_sync_d = gr::linalg::matrix_pseudo_inverse_sync_d;
  using matrix_pseudo_inverse_sync_c = gr::linalg::matrix_pseudo_inverse_sync_c;
  using matrix_pseudo_inverse_sync_cd =
      gr::linalg::matrix_pseudo_inverse_sync_cd;

  py::class_<matrix_pseudo_inverse_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_pseudo_inverse_sync_f>>(
      m, "matrix_pseudo_inverse_sync_f",
      "Matrix pseudo-inverse sync block (float)")

      .def(py::init(&matrix_pseudo_inverse_sync_f::make), py::arg("shape"),
           "Create matrix pseudo-inverse sync block")
      .def_static("make", &matrix_pseudo_inverse_sync_f::make, py::arg("shape"),
                  "Create matrix pseudo-inverse sync block");

  py::class_<matrix_pseudo_inverse_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_pseudo_inverse_sync_d>>(
      m, "matrix_pseudo_inverse_sync_d",
      "Matrix pseudo-inverse sync block (double)")

      .def(py::init(&matrix_pseudo_inverse_sync_d::make), py::arg("shape"),
           "Create matrix pseudo-inverse sync block")
      .def_static("make", &matrix_pseudo_inverse_sync_d::make, py::arg("shape"),
                  "Create matrix pseudo-inverse sync block");

  py::class_<matrix_pseudo_inverse_sync_c, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_pseudo_inverse_sync_c>>(
      m, "matrix_pseudo_inverse_sync_cf",
      "Matrix pseudo-inverse sync block (complex float)")

      .def(py::init(&matrix_pseudo_inverse_sync_c::make), py::arg("shape"),
           "Create matrix pseudo-inverse sync block")
      .def_static("make", &matrix_pseudo_inverse_sync_c::make, py::arg("shape"),
                  "Create matrix pseudo-inverse sync block");

  py::class_<matrix_pseudo_inverse_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_pseudo_inverse_sync_cd>>(
      m, "matrix_pseudo_inverse_sync_cd",
      "Matrix pseudo-inverse sync block (complex double)")

      .def(py::init(&matrix_pseudo_inverse_sync_cd::make), py::arg("shape"),
           "Create matrix pseudo-inverse sync block")
      .def_static("make", &matrix_pseudo_inverse_sync_cd::make,
                  py::arg("shape"), "Create matrix pseudo-inverse sync block");
}
