/*
 * Copyright 2025 Wylie Standage-Beier.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_correlation.h) */
/* BINDTOOL_HEADER_FILE_HASH(051eb35be74d48029049a302f6f337e6) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_correlation.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_correlation_pydoc.h>

void bind_matrix_correlation(py::module &m) {

  using matrix_correlation_sync_f = gr::linalg::matrix_correlation_sync_f;
  using matrix_correlation_sync_d = gr::linalg::matrix_correlation_sync_d;
  using matrix_correlation_sync_cf = gr::linalg::matrix_correlation_sync_cf;
  using matrix_correlation_sync_cd = gr::linalg::matrix_correlation_sync_cd;

  using matrix_correlation_pdu_f = gr::linalg::matrix_correlation_pdu_f;
  using matrix_correlation_pdu_d = gr::linalg::matrix_correlation_pdu_d;
  using matrix_correlation_pdu_cf = gr::linalg::matrix_correlation_pdu_cf;
  using matrix_correlation_pdu_cd = gr::linalg::matrix_correlation_pdu_cd;

  // Sync blocks - float
  py::class_<matrix_correlation_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_correlation_sync_f>>(
      m, "matrix_correlation_sync_f", D(matrix_correlation_sync_f))

      .def(py::init(&matrix_correlation_sync_f::make), py::arg("shape"),
           py::arg("method") = 0, D(matrix_correlation_sync_f, make))
      .def_static("make", &matrix_correlation_sync_f::make, py::arg("shape"),
                  py::arg("method") = 0, D(matrix_correlation_sync_f, make))
      .def("set_method", &matrix_correlation_sync_f::set_method,
           py::arg("method"), D(matrix_correlation_sync_f, set_method))
      .def("get_method", &matrix_correlation_sync_f::get_method,
           D(matrix_correlation_sync_f, get_method));

  // Sync blocks - double
  py::class_<matrix_correlation_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_correlation_sync_d>>(
      m, "matrix_correlation_sync_d", D(matrix_correlation_sync_d))

      .def(py::init(&matrix_correlation_sync_d::make), py::arg("shape"),
           py::arg("method") = 0, D(matrix_correlation_sync_d, make))
      .def_static("make", &matrix_correlation_sync_d::make, py::arg("shape"),
                  py::arg("method") = 0, D(matrix_correlation_sync_d, make))
      .def("set_method", &matrix_correlation_sync_d::set_method,
           py::arg("method"), D(matrix_correlation_sync_d, set_method))
      .def("get_method", &matrix_correlation_sync_d::get_method,
           D(matrix_correlation_sync_d, get_method));

  // Sync blocks - complex float
  py::class_<matrix_correlation_sync_cf, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_correlation_sync_cf>>(
      m, "matrix_correlation_sync_cf", D(matrix_correlation_sync_cf))

      .def(py::init(&matrix_correlation_sync_cf::make), py::arg("shape"),
           py::arg("method") = 0, D(matrix_correlation_sync_cf, make))
      .def_static("make", &matrix_correlation_sync_cf::make, py::arg("shape"),
                  py::arg("method") = 0, D(matrix_correlation_sync_cf, make))
      .def("set_method", &matrix_correlation_sync_cf::set_method,
           py::arg("method"), D(matrix_correlation_sync_cf, set_method))
      .def("get_method", &matrix_correlation_sync_cf::get_method,
           D(matrix_correlation_sync_cf, get_method));

  // Sync blocks - complex double
  py::class_<matrix_correlation_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_correlation_sync_cd>>(
      m, "matrix_correlation_sync_cd", D(matrix_correlation_sync_cd))

      .def(py::init(&matrix_correlation_sync_cd::make), py::arg("shape"),
           py::arg("method") = 0, D(matrix_correlation_sync_cd, make))
      .def_static("make", &matrix_correlation_sync_cd::make, py::arg("shape"),
                  py::arg("method") = 0, D(matrix_correlation_sync_cd, make))
      .def("set_method", &matrix_correlation_sync_cd::set_method,
           py::arg("method"), D(matrix_correlation_sync_cd, set_method))
      .def("get_method", &matrix_correlation_sync_cd::get_method,
           D(matrix_correlation_sync_cd, get_method));

  // PDU blocks - float
  py::class_<matrix_correlation_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_correlation_pdu_f>>(
      m, "matrix_correlation_pdu_f", D(matrix_correlation_pdu_f))

      .def(py::init(&matrix_correlation_pdu_f::make), py::arg("shape"),
           py::arg("method") = 0, D(matrix_correlation_pdu_f, make))
      .def_static("make", &matrix_correlation_pdu_f::make, py::arg("shape"),
                  py::arg("method") = 0, D(matrix_correlation_pdu_f, make))
      .def("set_method", &matrix_correlation_pdu_f::set_method,
           py::arg("method"), D(matrix_correlation_pdu_f, set_method))
      .def("get_method", &matrix_correlation_pdu_f::get_method,
           D(matrix_correlation_pdu_f, get_method));

  // PDU blocks - double
  py::class_<matrix_correlation_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_correlation_pdu_d>>(
      m, "matrix_correlation_pdu_d", D(matrix_correlation_pdu_d))

      .def(py::init(&matrix_correlation_pdu_d::make), py::arg("shape"),
           py::arg("method") = 0, D(matrix_correlation_pdu_d, make))
      .def_static("make", &matrix_correlation_pdu_d::make, py::arg("shape"),
                  py::arg("method") = 0, D(matrix_correlation_pdu_d, make))
      .def("set_method", &matrix_correlation_pdu_d::set_method,
           py::arg("method"), D(matrix_correlation_pdu_d, set_method))
      .def("get_method", &matrix_correlation_pdu_d::get_method,
           D(matrix_correlation_pdu_d, get_method));

  // PDU blocks - complex float
  py::class_<matrix_correlation_pdu_cf, gr::block, gr::basic_block,
             std::shared_ptr<matrix_correlation_pdu_cf>>(
      m, "matrix_correlation_pdu_cf", D(matrix_correlation_pdu_cf))

      .def(py::init(&matrix_correlation_pdu_cf::make), py::arg("shape"),
           py::arg("method") = 0, D(matrix_correlation_pdu_cf, make))
      .def_static("make", &matrix_correlation_pdu_cf::make, py::arg("shape"),
                  py::arg("method") = 0, D(matrix_correlation_pdu_cf, make))
      .def("set_method", &matrix_correlation_pdu_cf::set_method,
           py::arg("method"), D(matrix_correlation_pdu_cf, set_method))
      .def("get_method", &matrix_correlation_pdu_cf::get_method,
           D(matrix_correlation_pdu_cf, get_method));

  // PDU blocks - complex double
  py::class_<matrix_correlation_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_correlation_pdu_cd>>(
      m, "matrix_correlation_pdu_cd", D(matrix_correlation_pdu_cd))

      .def(py::init(&matrix_correlation_pdu_cd::make), py::arg("shape"),
           py::arg("method") = 0, D(matrix_correlation_pdu_cd, make))
      .def_static("make", &matrix_correlation_pdu_cd::make, py::arg("shape"),
                  py::arg("method") = 0, D(matrix_correlation_pdu_cd, make))
      .def("set_method", &matrix_correlation_pdu_cd::set_method,
           py::arg("method"), D(matrix_correlation_pdu_cd, set_method))
      .def("get_method", &matrix_correlation_pdu_cd::get_method,
           D(matrix_correlation_pdu_cd, get_method));
}