/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_diag.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(edcde8233cdc5b7ca1a51c79ebfdd837) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_diag.h>
// pydoc.h is automatically generated in the build directory
// #include <matrix_diag_pydoc.h>  // Commented out for now

void bind_matrix_diag(py::module &m) {
  using matrix_diag_sync_f = gr::linalg::matrix_diag_sync_f;
  using matrix_diag_sync_d = gr::linalg::matrix_diag_sync_d;
  using matrix_diag_sync_cf = gr::linalg::matrix_diag_sync_cf;
  using matrix_diag_sync_cd = gr::linalg::matrix_diag_sync_cd;

  py::class_<matrix_diag_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_diag_sync_f>>(
      m, "matrix_diag_sync_f", "Matrix diagonal extraction sync block (float)")

      .def(py::init(&matrix_diag_sync_f::make), py::arg("shape"), py::arg("k"),
           "Create matrix diagonal sync block")
      .def_static("make", &matrix_diag_sync_f::make, py::arg("shape"),
                  py::arg("k"), "Create matrix diagonal sync block");

  py::class_<matrix_diag_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_diag_sync_d>>(
      m, "matrix_diag_sync_d", "Matrix diagonal extraction sync block (double)")

      .def(py::init(&matrix_diag_sync_d::make), py::arg("shape"), py::arg("k"),
           "Create matrix diagonal sync block")
      .def_static("make", &matrix_diag_sync_d::make, py::arg("shape"),
                  py::arg("k"), "Create matrix diagonal sync block");

  py::class_<matrix_diag_sync_cf, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_diag_sync_cf>>(
      m, "matrix_diag_sync_cf",
      "Matrix diagonal extraction sync block (complex float)")

      .def(py::init(&matrix_diag_sync_cf::make), py::arg("shape"), py::arg("k"),
           "Create matrix diagonal sync block")
      .def_static("make", &matrix_diag_sync_cf::make, py::arg("shape"),
                  py::arg("k"), "Create matrix diagonal sync block");

  py::class_<matrix_diag_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_diag_sync_cd>>(
      m, "matrix_diag_sync_cd",
      "Matrix diagonal extraction sync block (complex double)")

      .def(py::init(&matrix_diag_sync_cd::make), py::arg("shape"), py::arg("k"),
           "Create matrix diagonal sync block")
      .def_static("make", &matrix_diag_sync_cd::make, py::arg("shape"),
                  py::arg("k"), "Create matrix diagonal sync block");
}
