/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_kronecker_product.h) */
/* BINDTOOL_HEADER_FILE_HASH(d80257a7672e5ddc8c3d69178064ece4) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_kronecker_product.h>
// pydoc.h is automatically generated in the build directory
// #include <matrix_kronecker_product_pydoc.h>  // Disabled until auto-generated

void bind_matrix_kronecker_product(py::module &m) {

  // Sync bindings for all precision variants
  using matrix_kronecker_product_sync_f =
      gr::linalg::matrix_kronecker_product_sync_f;
  using matrix_kronecker_product_sync_d =
      gr::linalg::matrix_kronecker_product_sync_d;
  using matrix_kronecker_product_sync_c =
      gr::linalg::matrix_kronecker_product_sync_c;
  using matrix_kronecker_product_sync_cd =
      gr::linalg::matrix_kronecker_product_sync_cd;

  py::class_<matrix_kronecker_product_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_kronecker_product_sync_f>>(
      m, "matrix_kronecker_product_sync_f",
      "Matrix Kronecker product sync block (float)")

      .def_static("make", &matrix_kronecker_product_sync_f::make,
                  py::arg("shape_a"), py::arg("shape_b"),
                  "Create matrix Kronecker product sync block");

  py::class_<matrix_kronecker_product_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_kronecker_product_sync_d>>(
      m, "matrix_kronecker_product_sync_d",
      "Matrix Kronecker product sync block (double)")

      .def_static("make", &matrix_kronecker_product_sync_d::make,
                  py::arg("shape_a"), py::arg("shape_b"),
                  "Create matrix Kronecker product sync block");

  py::class_<matrix_kronecker_product_sync_c, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_kronecker_product_sync_c>>(
      m, "matrix_kronecker_product_sync_c",
      "Matrix Kronecker product sync block (complex float)")

      .def_static("make", &matrix_kronecker_product_sync_c::make,
                  py::arg("shape_a"), py::arg("shape_b"),
                  "Create matrix Kronecker product sync block");

  py::class_<matrix_kronecker_product_sync_cd, gr::sync_block, gr::block,
             gr::basic_block,
             std::shared_ptr<matrix_kronecker_product_sync_cd>>(
      m, "matrix_kronecker_product_sync_cd",
      "Matrix Kronecker product sync block (complex double)")

      .def_static("make", &matrix_kronecker_product_sync_cd::make,
                  py::arg("shape_a"), py::arg("shape_b"),
                  "Create matrix Kronecker product sync block");

  // PDU bindings for all precision variants
  using matrix_kronecker_product_pdu_f =
      gr::linalg::matrix_kronecker_product_pdu_f;
  using matrix_kronecker_product_pdu_d =
      gr::linalg::matrix_kronecker_product_pdu_d;
  using matrix_kronecker_product_pdu_c =
      gr::linalg::matrix_kronecker_product_pdu_c;
  using matrix_kronecker_product_pdu_cd =
      gr::linalg::matrix_kronecker_product_pdu_cd;

  py::class_<matrix_kronecker_product_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_kronecker_product_pdu_f>>(
      m, "matrix_kronecker_product_pdu_f",
      "Matrix Kronecker product PDU block (float)")

      .def_static("make", &matrix_kronecker_product_pdu_f::make,
                  py::arg("shape_a"), py::arg("shape_b"),
                  "Create matrix Kronecker product PDU block");

  py::class_<matrix_kronecker_product_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_kronecker_product_pdu_d>>(
      m, "matrix_kronecker_product_pdu_d",
      "Matrix Kronecker product PDU block (double)")

      .def_static("make", &matrix_kronecker_product_pdu_d::make,
                  py::arg("shape_a"), py::arg("shape_b"),
                  "Create matrix Kronecker product PDU block");

  py::class_<matrix_kronecker_product_pdu_c, gr::block, gr::basic_block,
             std::shared_ptr<matrix_kronecker_product_pdu_c>>(
      m, "matrix_kronecker_product_pdu_c",
      "Matrix Kronecker product PDU block (complex float)")

      .def_static("make", &matrix_kronecker_product_pdu_c::make,
                  py::arg("shape_a"), py::arg("shape_b"),
                  "Create matrix Kronecker product PDU block");

  py::class_<matrix_kronecker_product_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_kronecker_product_pdu_cd>>(
      m, "matrix_kronecker_product_pdu_cd",
      "Matrix Kronecker product PDU block (complex double)")

      .def_static("make", &matrix_kronecker_product_pdu_cd::make,
                  py::arg("shape_a"), py::arg("shape_b"),
                  "Create matrix Kronecker product PDU block");
}