/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_pseudo_determinant.h) */
/* BINDTOOL_HEADER_FILE_HASH(de6a65ae6940fb252c7d3094f479984d) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_pseudo_determinant.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_pseudo_determinant_pydoc.h>

void bind_matrix_pseudo_determinant(py::module &m) {

  // Sync bindings for all precision variants
  using matrix_pseudo_determinant_sync_f =
      gr::linalg::matrix_pseudo_determinant_sync_f;
  using matrix_pseudo_determinant_sync_d =
      gr::linalg::matrix_pseudo_determinant_sync_d;
  using matrix_pseudo_determinant_sync_c =
      gr::linalg::matrix_pseudo_determinant_sync_c;
  using matrix_pseudo_determinant_sync_cd =
      gr::linalg::matrix_pseudo_determinant_sync_cd;

  py::class_<matrix_pseudo_determinant_sync_f, gr::sync_block, gr::block,
             gr::basic_block,
             std::shared_ptr<matrix_pseudo_determinant_sync_f>>(
      m, "matrix_pseudo_determinant_sync_f", D(matrix_pseudo_determinant))

      .def_static("make", &matrix_pseudo_determinant_sync_f::make,
                  D(matrix_pseudo_determinant, make));

  py::class_<matrix_pseudo_determinant_sync_d, gr::sync_block, gr::block,
             gr::basic_block,
             std::shared_ptr<matrix_pseudo_determinant_sync_d>>(
      m, "matrix_pseudo_determinant_sync_d", D(matrix_pseudo_determinant))

      .def_static("make", &matrix_pseudo_determinant_sync_d::make,
                  D(matrix_pseudo_determinant, make));

  py::class_<matrix_pseudo_determinant_sync_c, gr::sync_block, gr::block,
             gr::basic_block,
             std::shared_ptr<matrix_pseudo_determinant_sync_c>>(
      m, "matrix_pseudo_determinant_sync_c", D(matrix_pseudo_determinant))

      .def_static("make", &matrix_pseudo_determinant_sync_c::make,
                  D(matrix_pseudo_determinant, make));

  py::class_<matrix_pseudo_determinant_sync_cd, gr::sync_block, gr::block,
             gr::basic_block,
             std::shared_ptr<matrix_pseudo_determinant_sync_cd>>(
      m, "matrix_pseudo_determinant_sync_cd", D(matrix_pseudo_determinant))

      .def_static("make", &matrix_pseudo_determinant_sync_cd::make,
                  D(matrix_pseudo_determinant, make));

  // PDU bindings for all precision variants
  using matrix_pseudo_determinant_pdu_f =
      gr::linalg::matrix_pseudo_determinant_pdu_f;
  using matrix_pseudo_determinant_pdu_d =
      gr::linalg::matrix_pseudo_determinant_pdu_d;
  using matrix_pseudo_determinant_pdu_c =
      gr::linalg::matrix_pseudo_determinant_pdu_c;
  using matrix_pseudo_determinant_pdu_cd =
      gr::linalg::matrix_pseudo_determinant_pdu_cd;

  py::class_<matrix_pseudo_determinant_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_pseudo_determinant_pdu_f>>(
      m, "matrix_pseudo_determinant_pdu_f", D(matrix_pseudo_determinant))

      .def_static("make", &matrix_pseudo_determinant_pdu_f::make,
                  D(matrix_pseudo_determinant, make));

  py::class_<matrix_pseudo_determinant_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_pseudo_determinant_pdu_d>>(
      m, "matrix_pseudo_determinant_pdu_d", D(matrix_pseudo_determinant))

      .def_static("make", &matrix_pseudo_determinant_pdu_d::make,
                  D(matrix_pseudo_determinant, make));

  py::class_<matrix_pseudo_determinant_pdu_c, gr::block, gr::basic_block,
             std::shared_ptr<matrix_pseudo_determinant_pdu_c>>(
      m, "matrix_pseudo_determinant_pdu_c", D(matrix_pseudo_determinant))

      .def_static("make", &matrix_pseudo_determinant_pdu_c::make,
                  D(matrix_pseudo_determinant, make));

  py::class_<matrix_pseudo_determinant_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_pseudo_determinant_pdu_cd>>(
      m, "matrix_pseudo_determinant_pdu_cd", D(matrix_pseudo_determinant))

      .def_static("make", &matrix_pseudo_determinant_pdu_cd::make,
                  D(matrix_pseudo_determinant, make));
}
