/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_trig.h) */
/* BINDTOOL_HEADER_FILE_HASH(e15b0676c89c85a05cea659ee3f4bec6) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_trig.h>
// pydoc.h is automatically generated in the build directory
// #include <matrix_cos_pydoc.h>  // Disabled until auto-generated

void bind_matrix_cos(py::module &m) {

  // Sync bindings for all precision variants
  using matrix_cos_sync_f = gr::linalg::matrix_cos_sync_f;
  using matrix_cos_sync_d = gr::linalg::matrix_cos_sync_d;
  using matrix_cos_sync_c = gr::linalg::matrix_cos_sync_cf;
  using matrix_cos_sync_cd = gr::linalg::matrix_cos_sync_cd;

  py::class_<matrix_cos_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_cos_sync_f>>(
      m, "matrix_cos_sync_f", "Matrix cosine sync block (float)")

      .def_static(
          "make",
          [](const std::vector<std::vector<int>> &input_shapes,
             gr::linalg::TrigAlgorithm algorithm, int max_iterations,
             double tolerance) {
            return matrix_cos_sync_f::make(input_shapes, algorithm,
                                           max_iterations, tolerance);
          },
          py::arg("input_shapes"),
          py::arg("algorithm") = gr::linalg::TrigAlgorithm::AUTO,
          py::arg("max_iterations") = 100, py::arg("tolerance") = 1e-10,
          "Create matrix cosine sync block");

  py::class_<matrix_cos_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_cos_sync_d>>(
      m, "matrix_cos_sync_d", "Matrix cosine sync block (double)")

      .def_static(
          "make",
          [](const std::vector<std::vector<int>> &input_shapes,
             gr::linalg::TrigAlgorithm algorithm, int max_iterations,
             double tolerance) {
            return matrix_cos_sync_d::make(input_shapes, algorithm,
                                           max_iterations, tolerance);
          },
          py::arg("input_shapes"),
          py::arg("algorithm") = gr::linalg::TrigAlgorithm::AUTO,
          py::arg("max_iterations") = 100, py::arg("tolerance") = 1e-10,
          "Create matrix cosine sync block");

  py::class_<matrix_cos_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_cos_sync_c>>(
      m, "matrix_cos_sync_c", "Matrix cosine sync block (complex float)")

      .def_static(
          "make",
          [](const std::vector<std::vector<int>> &input_shapes,
             gr::linalg::TrigAlgorithm algorithm, int max_iterations,
             double tolerance) {
            return matrix_cos_sync_c::make(input_shapes, algorithm,
                                           max_iterations, tolerance);
          },
          py::arg("input_shapes"),
          py::arg("algorithm") = gr::linalg::TrigAlgorithm::AUTO,
          py::arg("max_iterations") = 100, py::arg("tolerance") = 1e-10,
          "Create matrix cosine sync block");

  py::class_<matrix_cos_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_cos_sync_cd>>(
      m, "matrix_cos_sync_cd", "Matrix cosine sync block (complex double)")

      .def_static(
          "make",
          [](const std::vector<std::vector<int>> &input_shapes,
             gr::linalg::TrigAlgorithm algorithm, int max_iterations,
             double tolerance) {
            return matrix_cos_sync_cd::make(input_shapes, algorithm,
                                            max_iterations, tolerance);
          },
          py::arg("input_shapes"),
          py::arg("algorithm") = gr::linalg::TrigAlgorithm::AUTO,
          py::arg("max_iterations") = 100, py::arg("tolerance") = 1e-10,
          "Create matrix cosine sync block");

  // PDU bindings for all precision variants
  using matrix_cos_pdu_f = gr::linalg::matrix_cos_pdu_f;
  using matrix_cos_pdu_d = gr::linalg::matrix_cos_pdu_d;
  using matrix_cos_pdu_c = gr::linalg::matrix_cos_pdu_cf;
  using matrix_cos_pdu_cd = gr::linalg::matrix_cos_pdu_cd;

  py::class_<matrix_cos_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_cos_pdu_f>>(
      m, "matrix_cos_pdu_f", "Matrix cosine PDU block (float)")

      .def_static(
          "make",
          [](const std::vector<std::vector<int>> &input_shapes,
             gr::linalg::TrigAlgorithm algorithm, int max_iterations,
             double tolerance) {
            return matrix_cos_pdu_f::make(input_shapes, algorithm,
                                          max_iterations, tolerance);
          },
          py::arg("input_shapes"),
          py::arg("algorithm") = gr::linalg::TrigAlgorithm::AUTO,
          py::arg("max_iterations") = 100, py::arg("tolerance") = 1e-10,
          "Create matrix cosine PDU block");

  py::class_<matrix_cos_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_cos_pdu_d>>(
      m, "matrix_cos_pdu_d", "Matrix cosine PDU block (double)")

      .def_static(
          "make",
          [](const std::vector<std::vector<int>> &input_shapes,
             gr::linalg::TrigAlgorithm algorithm, int max_iterations,
             double tolerance) {
            return matrix_cos_pdu_d::make(input_shapes, algorithm,
                                          max_iterations, tolerance);
          },
          py::arg("input_shapes"),
          py::arg("algorithm") = gr::linalg::TrigAlgorithm::AUTO,
          py::arg("max_iterations") = 100, py::arg("tolerance") = 1e-10,
          "Create matrix cosine PDU block");

  py::class_<matrix_cos_pdu_c, gr::block, gr::basic_block,
             std::shared_ptr<matrix_cos_pdu_c>>(
      m, "matrix_cos_pdu_c", "Matrix cosine PDU block (complex float)")

      .def_static(
          "make",
          [](const std::vector<std::vector<int>> &input_shapes,
             gr::linalg::TrigAlgorithm algorithm, int max_iterations,
             double tolerance) {
            return matrix_cos_pdu_c::make(input_shapes, algorithm,
                                          max_iterations, tolerance);
          },
          py::arg("input_shapes"),
          py::arg("algorithm") = gr::linalg::TrigAlgorithm::AUTO,
          py::arg("max_iterations") = 100, py::arg("tolerance") = 1e-10,
          "Create matrix cosine PDU block");

  py::class_<matrix_cos_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_cos_pdu_cd>>(
      m, "matrix_cos_pdu_cd", "Matrix cosine PDU block (complex double)")

      .def_static(
          "make",
          [](const std::vector<std::vector<int>> &input_shapes,
             gr::linalg::TrigAlgorithm algorithm, int max_iterations,
             double tolerance) {
            return matrix_cos_pdu_cd::make(input_shapes, algorithm,
                                           max_iterations, tolerance);
          },
          py::arg("input_shapes"),
          py::arg("algorithm") = gr::linalg::TrigAlgorithm::AUTO,
          py::arg("max_iterations") = 100, py::arg("tolerance") = 1e-10,
          "Create matrix cosine PDU block");
}