/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_log.h) */
/* BINDTOOL_HEADER_FILE_HASH(9514fb6e135fb8a07373a98dcf148c5b) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_log.h>
// pydoc.h is automatically generated in the build directory
// #include <matrix_log_pydoc.h>  // Disabled until auto-generated

void bind_matrix_log(py::module &m) {

  // Sync bindings for all precision variants
  using matrix_log_sync_f = gr::linalg::matrix_log_sync_f;
  using matrix_log_sync_d = gr::linalg::matrix_log_sync_d;
  using matrix_log_sync_c = gr::linalg::matrix_log_sync_cf;
  using matrix_log_sync_cd = gr::linalg::matrix_log_sync_cd;

  py::class_<matrix_log_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_log_sync_f>>(
      m, "matrix_log_sync_f", "Matrix logarithm sync block (float)")

      .def_static("make", &matrix_log_sync_f::make,
                  "Create matrix logarithm sync block");

  py::class_<matrix_log_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_log_sync_d>>(
      m, "matrix_log_sync_d", "Matrix logarithm sync block (double)")

      .def_static("make", &matrix_log_sync_d::make,
                  "Create matrix logarithm sync block");

  py::class_<matrix_log_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_log_sync_c>>(
      m, "matrix_log_sync_c", "Matrix logarithm sync block (complex float)")

      .def_static("make", &matrix_log_sync_c::make,
                  "Create matrix logarithm sync block");

  py::class_<matrix_log_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_log_sync_cd>>(
      m, "matrix_log_sync_cd", "Matrix logarithm sync block (complex double)")

      .def_static("make", &matrix_log_sync_cd::make,
                  "Create matrix logarithm sync block");

  // PDU bindings for all precision variants
  using matrix_log_pdu_f = gr::linalg::matrix_log_pdu_f;
  using matrix_log_pdu_d = gr::linalg::matrix_log_pdu_d;
  using matrix_log_pdu_c = gr::linalg::matrix_log_pdu_cf;
  using matrix_log_pdu_cd = gr::linalg::matrix_log_pdu_cd;

  py::class_<matrix_log_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_log_pdu_f>>(
      m, "matrix_log_pdu_f", "Matrix logarithm PDU block (float)")

      .def_static("make", &matrix_log_pdu_f::make,
                  "Create matrix logarithm PDU block");

  py::class_<matrix_log_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_log_pdu_d>>(
      m, "matrix_log_pdu_d", "Matrix logarithm PDU block (double)")

      .def_static("make", &matrix_log_pdu_d::make,
                  "Create matrix logarithm PDU block");

  py::class_<matrix_log_pdu_c, gr::block, gr::basic_block,
             std::shared_ptr<matrix_log_pdu_c>>(
      m, "matrix_log_pdu_c", "Matrix logarithm PDU block (complex float)")

      .def_static("make", &matrix_log_pdu_c::make,
                  "Create matrix logarithm PDU block");

  py::class_<matrix_log_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_log_pdu_cd>>(
      m, "matrix_log_pdu_cd", "Matrix logarithm PDU block (complex double)")

      .def_static("make", &matrix_log_pdu_cd::make,
                  "Create matrix logarithm PDU block");
}