/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_elementwise_divide.h) */
/* BINDTOOL_HEADER_FILE_HASH(e1f0917a6f4c5f9929aa513440cf87f3) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_elementwise_divide.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_elementwise_divide_pydoc.h>

void bind_matrix_elementwise_divide(py::module &m) {

  using matrix_elementwise_divide_sync =
      gr::linalg::matrix_elementwise_divide_sync<float>;
  using matrix_elementwise_divide_sync_d =
      gr::linalg::matrix_elementwise_divide_sync<double>;
  using matrix_elementwise_divide_sync_cf =
      gr::linalg::matrix_elementwise_divide_sync<std::complex<float>>;
  using matrix_elementwise_divide_sync_cd =
      gr::linalg::matrix_elementwise_divide_sync<std::complex<double>>;

  py::class_<matrix_elementwise_divide_sync, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_elementwise_divide_sync>>(
      m, "matrix_elementwise_divide_sync_f", D(matrix_elementwise_divide_sync))

      .def_static("make", &matrix_elementwise_divide_sync::make,
                  D(matrix_elementwise_divide_sync, make));

  py::class_<matrix_elementwise_divide_sync_d, gr::sync_block, gr::block,
             gr::basic_block,
             std::shared_ptr<matrix_elementwise_divide_sync_d>>(
      m, "matrix_elementwise_divide_sync_d", D(matrix_elementwise_divide_sync))

      .def_static("make", &matrix_elementwise_divide_sync_d::make,
                  D(matrix_elementwise_divide_sync, make));

  py::class_<matrix_elementwise_divide_sync_cf, gr::sync_block, gr::block,
             gr::basic_block,
             std::shared_ptr<matrix_elementwise_divide_sync_cf>>(
      m, "matrix_elementwise_divide_sync_c", D(matrix_elementwise_divide_sync))

      .def_static("make", &matrix_elementwise_divide_sync_cf::make,
                  D(matrix_elementwise_divide_sync, make));

  py::class_<matrix_elementwise_divide_sync_cd, gr::sync_block, gr::block,
             gr::basic_block,
             std::shared_ptr<matrix_elementwise_divide_sync_cd>>(
      m, "matrix_elementwise_divide_sync_cd", D(matrix_elementwise_divide_sync))

      .def_static("make", &matrix_elementwise_divide_sync_cd::make,
                  D(matrix_elementwise_divide_sync, make));
}