/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_multiply.h) */
/* BINDTOOL_HEADER_FILE_HASH(0cd9601d4d9befae8881b972dd79982c) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_multiply.h>
// Include implementation details for template instantiation
#include "../../../../lib/matrix_multiply_impl.h"
// pydoc.h is automatically generated in the build directory
#include <matrix_multiply_pydoc.h>

void bind_matrix_multiply(py::module &m) {
  // Sync blocks
  using matrix_multiply_sync_f = gr::linalg::matrix_multiply_sync_f;
  using matrix_multiply_sync_d = gr::linalg::matrix_multiply_sync_d;
  using matrix_multiply_sync_c = gr::linalg::matrix_multiply_sync_c;
  using matrix_multiply_sync_z = gr::linalg::matrix_multiply_sync_z;

  // PDU blocks
  using matrix_multiply_pdu_f = gr::linalg::matrix_multiply_pdu_f;
  using matrix_multiply_pdu_d = gr::linalg::matrix_multiply_pdu_d;
  using matrix_multiply_pdu_c = gr::linalg::matrix_multiply_pdu_c;
  using matrix_multiply_pdu_z = gr::linalg::matrix_multiply_pdu_z;

  // Float sync block
  py::class_<matrix_multiply_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_multiply_sync_f>>(m,
                                                      "matrix_multiply_sync_f")

      .def(py::init(&matrix_multiply_sync_f::make), py::arg("shape_0"),
           py::arg("shape_1"))
      .def_static("make", &matrix_multiply_sync_f::make, py::arg("shape_0"),
                  py::arg("shape_1"));

  // Double sync block
  py::class_<matrix_multiply_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_multiply_sync_d>>(m,
                                                      "matrix_multiply_sync_d")

      .def(py::init(&matrix_multiply_sync_d::make), py::arg("shape_0"),
           py::arg("shape_1"))
      .def_static("make", &matrix_multiply_sync_d::make, py::arg("shape_0"),
                  py::arg("shape_1"));

  // Complex float sync block
  py::class_<matrix_multiply_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_multiply_sync_c>>(m,
                                                      "matrix_multiply_sync_c")

      .def(py::init(&matrix_multiply_sync_c::make), py::arg("shape_0"),
           py::arg("shape_1"))
      .def_static("make", &matrix_multiply_sync_c::make, py::arg("shape_0"),
                  py::arg("shape_1"));

  // Complex double sync block
  py::class_<matrix_multiply_sync_z, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_multiply_sync_z>>(m,
                                                      "matrix_multiply_sync_z")

      .def(py::init(&matrix_multiply_sync_z::make), py::arg("shape_0"),
           py::arg("shape_1"))
      .def_static("make", &matrix_multiply_sync_z::make, py::arg("shape_0"),
                  py::arg("shape_1"));

  // Float PDU block
  py::class_<matrix_multiply_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_multiply_pdu_f>>(m, "matrix_multiply_pdu_f")

      .def(py::init(&matrix_multiply_pdu_f::make), py::arg("shape_0"),
           py::arg("shape_1"))
      .def_static("make", &matrix_multiply_pdu_f::make, py::arg("shape_0"),
                  py::arg("shape_1"));

  // Double PDU block
  py::class_<matrix_multiply_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_multiply_pdu_d>>(m, "matrix_multiply_pdu_d")

      .def(py::init(&matrix_multiply_pdu_d::make), py::arg("shape_0"),
           py::arg("shape_1"))
      .def_static("make", &matrix_multiply_pdu_d::make, py::arg("shape_0"),
                  py::arg("shape_1"));

  // Complex float PDU block
  py::class_<matrix_multiply_pdu_c, gr::block, gr::basic_block,
             std::shared_ptr<matrix_multiply_pdu_c>>(m, "matrix_multiply_pdu_c")

      .def(py::init(&matrix_multiply_pdu_c::make), py::arg("shape_0"),
           py::arg("shape_1"))
      .def_static("make", &matrix_multiply_pdu_c::make, py::arg("shape_0"),
                  py::arg("shape_1"));

  // Complex double PDU block
  py::class_<matrix_multiply_pdu_z, gr::block, gr::basic_block,
             std::shared_ptr<matrix_multiply_pdu_z>>(m, "matrix_multiply_pdu_z")

      .def(py::init(&matrix_multiply_pdu_z::make), py::arg("shape_0"),
           py::arg("shape_1"))
      .def_static("make", &matrix_multiply_pdu_z::make, py::arg("shape_0"),
                  py::arg("shape_1"));
}
