/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_power.h) */
/* BINDTOOL_HEADER_FILE_HASH(e96ff1eab600791c8d34f3fecbdbb037) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_power.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_power_pydoc.h>

void bind_matrix_power(py::module &m) {

  using matrix_power_sync = gr::linalg::matrix_power_sync<float>;
  using matrix_power_sync_d = gr::linalg::matrix_power_sync<double>;
  using matrix_power_sync_cf =
      gr::linalg::matrix_power_sync<std::complex<float>>;
  using matrix_power_sync_cd =
      gr::linalg::matrix_power_sync<std::complex<double>>;

  py::class_<matrix_power_sync, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_power_sync>>(m, "matrix_power_sync_f",
                                                 D(matrix_power_sync))

      .def_static("make", &matrix_power_sync::make, D(matrix_power_sync, make));

  py::class_<matrix_power_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_power_sync_d>>(m, "matrix_power_sync_d",
                                                   D(matrix_power_sync))

      .def_static("make", &matrix_power_sync_d::make,
                  D(matrix_power_sync, make));

  py::class_<matrix_power_sync_cf, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_power_sync_cf>>(m, "matrix_power_sync_c",
                                                    D(matrix_power_sync))

      .def_static("make", &matrix_power_sync_cf::make,
                  D(matrix_power_sync, make));

  py::class_<matrix_power_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_power_sync_cd>>(m, "matrix_power_sync_cd",
                                                    D(matrix_power_sync))

      .def_static("make", &matrix_power_sync_cd::make,
                  D(matrix_power_sync, make));
}