/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_subtract.h) */
/* BINDTOOL_HEADER_FILE_HASH(94bd5b6538623bec06867c4ed5f25ecf) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_subtract.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_subtract_pydoc.h>

void bind_matrix_subtract(py::module &m) {

  using matrix_subtract_sync_f = gr::linalg::matrix_subtract_sync_f;
  using matrix_subtract_sync_d = gr::linalg::matrix_subtract_sync_d;

  py::class_<matrix_subtract_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_subtract_sync_f>>(
      m, "matrix_subtract_sync_f", D(matrix_subtract))

      .def(py::init(&matrix_subtract_sync_f::make), py::arg("shape"),
           py::arg("num_inputs"), D(matrix_subtract, make))
      .def_static("make", &matrix_subtract_sync_f::make, py::arg("shape"),
                  py::arg("num_inputs"), D(matrix_subtract, make));

  py::class_<matrix_subtract_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_subtract_sync_d>>(
      m, "matrix_subtract_sync_d", D(matrix_subtract))

      .def(py::init(&matrix_subtract_sync_d::make), py::arg("shape"),
           py::arg("num_inputs"), D(matrix_subtract, make))
      .def_static("make", &matrix_subtract_sync_d::make, py::arg("shape"),
                  py::arg("num_inputs"), D(matrix_subtract, make));
}
