/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_determinant.h) */
/* BINDTOOL_HEADER_FILE_HASH(e890cf1b120f608c86aa815961cc2d7c) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_determinant.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_determinant_pydoc.h>

void bind_matrix_determinant(py::module &m) {

  using matrix_determinant_sync_f = gr::linalg::matrix_determinant_sync_f;
  using matrix_determinant_sync_d = gr::linalg::matrix_determinant_sync_d;

  py::class_<matrix_determinant_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_determinant_sync_f>>(
      m, "matrix_determinant_sync_f", D(matrix_determinant))

      .def(py::init(&matrix_determinant_sync_f::make),
           D(matrix_determinant, make));

  py::class_<matrix_determinant_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_determinant_sync_d>>(
      m, "matrix_determinant_sync_d", D(matrix_determinant))

      .def(py::init(&matrix_determinant_sync_d::make),
           D(matrix_determinant, make));
}
