/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_source_const.h) */
/* BINDTOOL_HEADER_FILE_HASH(5378728b6dc08056604f9cd99aa823b9) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_source_const.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_source_const_pydoc.h>

void bind_matrix_source_const(py::module &m) {

  using matrix_source_const_sync_f =
      gr::linalg::matrix_source_const_sync<float>;
  using matrix_source_const_sync_d =
      gr::linalg::matrix_source_const_sync<double>;
  using matrix_source_const_sync_cf =
      gr::linalg::matrix_source_const_sync<std::complex<float>>;
  using matrix_source_const_sync_cd =
      gr::linalg::matrix_source_const_sync<std::complex<double>>;

  using matrix_source_const_pdu_f = gr::linalg::matrix_source_const_pdu<float>;
  using matrix_source_const_pdu_d = gr::linalg::matrix_source_const_pdu<double>;
  using matrix_source_const_pdu_cf =
      gr::linalg::matrix_source_const_pdu<std::complex<float>>;
  using matrix_source_const_pdu_cd =
      gr::linalg::matrix_source_const_pdu<std::complex<double>>;

  // Sync float
  py::class_<matrix_source_const_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_source_const_sync_f>>(
      m, "matrix_source_const_sync_f", D(matrix_source_const))
      .def_static(
          "make",
          py::overload_cast<
              const Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic> &,
              const gr::linalg::types::shape &>(
              &matrix_source_const_sync_f::make),
          py::arg("matrix"), py::arg("shape"), D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<std::vector<float>> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_f::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<float> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_f::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make));

  // Sync double
  py::class_<matrix_source_const_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_source_const_sync_d>>(
      m, "matrix_source_const_sync_d", D(matrix_source_const))
      .def_static(
          "make",
          py::overload_cast<
              const Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> &,
              const gr::linalg::types::shape &>(
              &matrix_source_const_sync_d::make),
          py::arg("matrix"), py::arg("shape"), D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<std::vector<double>> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_d::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<double> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_d::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make));

  // Sync complex float
  py::class_<matrix_source_const_sync_cf, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_source_const_sync_cf>>(
      m, "matrix_source_const_sync_cf", D(matrix_source_const))
      .def_static("make",
                  py::overload_cast<
                      const Eigen::Matrix<std::complex<float>, Eigen::Dynamic,
                                          Eigen::Dynamic> &,
                      const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_cf::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<
                      const std::vector<std::vector<std::complex<float>>> &,
                      const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_cf::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<std::complex<float>> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_cf::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make));

  // Sync complex double
  py::class_<matrix_source_const_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_source_const_sync_cd>>(
      m, "matrix_source_const_sync_cd", D(matrix_source_const))
      .def_static("make",
                  py::overload_cast<
                      const Eigen::Matrix<std::complex<double>, Eigen::Dynamic,
                                          Eigen::Dynamic> &,
                      const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_cd::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<
                      const std::vector<std::vector<std::complex<double>>> &,
                      const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_cd::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<std::complex<double>> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_sync_cd::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make));

  // PDU float
  py::class_<matrix_source_const_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_source_const_pdu_f>>(
      m, "matrix_source_const_pdu_f", D(matrix_source_const))
      .def_static(
          "make",
          py::overload_cast<
              const Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic> &,
              const gr::linalg::types::shape &>(
              &matrix_source_const_pdu_f::make),
          py::arg("matrix"), py::arg("shape"), D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<std::vector<float>> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_f::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<float> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_f::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make));

  // PDU double
  py::class_<matrix_source_const_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_source_const_pdu_d>>(
      m, "matrix_source_const_pdu_d", D(matrix_source_const))
      .def_static(
          "make",
          py::overload_cast<
              const Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> &,
              const gr::linalg::types::shape &>(
              &matrix_source_const_pdu_d::make),
          py::arg("matrix"), py::arg("shape"), D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<std::vector<double>> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_d::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<double> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_d::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make));

  // PDU complex float
  py::class_<matrix_source_const_pdu_cf, gr::block, gr::basic_block,
             std::shared_ptr<matrix_source_const_pdu_cf>>(
      m, "matrix_source_const_pdu_cf", D(matrix_source_const))
      .def_static("make",
                  py::overload_cast<
                      const Eigen::Matrix<std::complex<float>, Eigen::Dynamic,
                                          Eigen::Dynamic> &,
                      const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_cf::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<
                      const std::vector<std::vector<std::complex<float>>> &,
                      const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_cf::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<std::complex<float>> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_cf::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make));

  // PDU complex double
  py::class_<matrix_source_const_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_source_const_pdu_cd>>(
      m, "matrix_source_const_pdu_cd", D(matrix_source_const))
      .def_static("make",
                  py::overload_cast<
                      const Eigen::Matrix<std::complex<double>, Eigen::Dynamic,
                                          Eigen::Dynamic> &,
                      const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_cd::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<
                      const std::vector<std::vector<std::complex<double>>> &,
                      const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_cd::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make))
      .def_static("make",
                  py::overload_cast<const std::vector<std::complex<double>> &,
                                    const gr::linalg::types::shape &>(
                      &matrix_source_const_pdu_cd::make),
                  py::arg("matrix"), py::arg("shape"),
                  D(matrix_source_const, make));
}
