/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_eigenvalues.h) */
/* BINDTOOL_HEADER_FILE_HASH(886fd999ad6288fec1183dac8910b0e6) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_eigenvalues.h>
// pydoc.h is automatically generated in the build directory
// #include <matrix_eigenvalues_pydoc.h>  // Disabled until auto-generated

void bind_matrix_eigenvalues(py::module &m) {
  // Sync bindings for all precision variants
  using matrix_eigenvalues_sync_f = gr::linalg::matrix_eigenvalues_sync_f;
  using matrix_eigenvalues_sync_d = gr::linalg::matrix_eigenvalues_sync_d;
  using matrix_eigenvalues_sync_cf = gr::linalg::matrix_eigenvalues_sync_cf;
  using matrix_eigenvalues_sync_cd = gr::linalg::matrix_eigenvalues_sync_cd;

  py::class_<matrix_eigenvalues_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_eigenvalues_sync_f>>(
      m, "matrix_eigenvalues_sync_f", "Matrix eigenvalues sync block (float)")

      .def_static("make", &matrix_eigenvalues_sync_f::make, py::arg("shape"),
                  py::arg("sort_by_magnitude") = true,
                  "Create matrix eigenvalues sync block")

      .def(
          "set_sort_by_magnitude",
          [](matrix_eigenvalues_sync_f &self, bool sort) {
            self.set_sort_by_magnitude(sort);
          },
          "Set eigenvalue sorting mode")
      .def(
          "get_sort_by_magnitude",
          [](matrix_eigenvalues_sync_f &self) {
            return self.get_sort_by_magnitude();
          },
          "Get eigenvalue sorting mode");

  py::class_<matrix_eigenvalues_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_eigenvalues_sync_d>>(
      m, "matrix_eigenvalues_sync_d", "Matrix eigenvalues sync block (double)")

      .def_static("make", &matrix_eigenvalues_sync_d::make, py::arg("shape"),
                  py::arg("sort_by_magnitude") = true,
                  "Create matrix eigenvalues sync block")

      .def(
          "set_sort_by_magnitude",
          [](matrix_eigenvalues_sync_d &self, bool sort) {
            self.set_sort_by_magnitude(sort);
          },
          "Set eigenvalue sorting mode")
      .def(
          "get_sort_by_magnitude",
          [](matrix_eigenvalues_sync_d &self) {
            return self.get_sort_by_magnitude();
          },
          "Get eigenvalue sorting mode");

  py::class_<matrix_eigenvalues_sync_cf, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_eigenvalues_sync_cf>>(
      m, "matrix_eigenvalues_sync_cf",
      "Matrix eigenvalues sync block (complex float)")

      .def_static("make", &matrix_eigenvalues_sync_cf::make, py::arg("shape"),
                  py::arg("sort_by_magnitude") = true,
                  "Create matrix eigenvalues sync block")

      .def(
          "set_sort_by_magnitude",
          [](matrix_eigenvalues_sync_cf &self, bool sort) {
            self.set_sort_by_magnitude(sort);
          },
          "Set eigenvalue sorting mode")
      .def(
          "get_sort_by_magnitude",
          [](matrix_eigenvalues_sync_cf &self) {
            return self.get_sort_by_magnitude();
          },
          "Get eigenvalue sorting mode");

  py::class_<matrix_eigenvalues_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_eigenvalues_sync_cd>>(
      m, "matrix_eigenvalues_sync_cd",
      "Matrix eigenvalues sync block (complex double)")

      .def_static("make", &matrix_eigenvalues_sync_cd::make, py::arg("shape"),
                  py::arg("sort_by_magnitude") = true,
                  "Create matrix eigenvalues sync block")

      .def(
          "set_sort_by_magnitude",
          [](matrix_eigenvalues_sync_cd &self, bool sort) {
            self.set_sort_by_magnitude(sort);
          },
          "Set eigenvalue sorting mode")
      .def(
          "get_sort_by_magnitude",
          [](matrix_eigenvalues_sync_cd &self) {
            return self.get_sort_by_magnitude();
          },
          "Get eigenvalue sorting mode");

  // PDU bindings for all precision variants
  using matrix_eigenvalues_pdu_f = gr::linalg::matrix_eigenvalues_pdu_f;
  using matrix_eigenvalues_pdu_d = gr::linalg::matrix_eigenvalues_pdu_d;
  using matrix_eigenvalues_pdu_cf = gr::linalg::matrix_eigenvalues_pdu_cf;
  using matrix_eigenvalues_pdu_cd = gr::linalg::matrix_eigenvalues_pdu_cd;

  py::class_<matrix_eigenvalues_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_eigenvalues_pdu_f>>(
      m, "matrix_eigenvalues_pdu_f", "Matrix eigenvalues PDU block (float)")

      .def_static("make", &matrix_eigenvalues_pdu_f::make, py::arg("shape"),
                  py::arg("sort_by_magnitude") = true,
                  "Create matrix eigenvalues PDU block")

      .def(
          "set_sort_by_magnitude",
          [](matrix_eigenvalues_pdu_f &self, bool sort) {
            self.set_sort_by_magnitude(sort);
          },
          "Set eigenvalue sorting mode")
      .def(
          "get_sort_by_magnitude",
          [](matrix_eigenvalues_pdu_f &self) {
            return self.get_sort_by_magnitude();
          },
          "Get eigenvalue sorting mode");

  py::class_<matrix_eigenvalues_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_eigenvalues_pdu_d>>(
      m, "matrix_eigenvalues_pdu_d", "Matrix eigenvalues PDU block (double)")

      .def_static("make", &matrix_eigenvalues_pdu_d::make, py::arg("shape"),
                  py::arg("sort_by_magnitude") = true,
                  "Create matrix eigenvalues PDU block")

      .def(
          "set_sort_by_magnitude",
          [](matrix_eigenvalues_pdu_d &self, bool sort) {
            self.set_sort_by_magnitude(sort);
          },
          "Set eigenvalue sorting mode")
      .def(
          "get_sort_by_magnitude",
          [](matrix_eigenvalues_pdu_d &self) {
            return self.get_sort_by_magnitude();
          },
          "Get eigenvalue sorting mode");

  py::class_<matrix_eigenvalues_pdu_cf, gr::block, gr::basic_block,
             std::shared_ptr<matrix_eigenvalues_pdu_cf>>(
      m, "matrix_eigenvalues_pdu_cf",
      "Matrix eigenvalues PDU block (complex float)")

      .def_static("make", &matrix_eigenvalues_pdu_cf::make, py::arg("shape"),
                  py::arg("sort_by_magnitude") = true,
                  "Create matrix eigenvalues PDU block")

      .def(
          "set_sort_by_magnitude",
          [](matrix_eigenvalues_pdu_cf &self, bool sort) {
            self.set_sort_by_magnitude(sort);
          },
          "Set eigenvalue sorting mode")
      .def(
          "get_sort_by_magnitude",
          [](matrix_eigenvalues_pdu_cf &self) {
            return self.get_sort_by_magnitude();
          },
          "Get eigenvalue sorting mode");

  py::class_<matrix_eigenvalues_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_eigenvalues_pdu_cd>>(
      m, "matrix_eigenvalues_pdu_cd",
      "Matrix eigenvalues PDU block (complex double)")

      .def_static("make", &matrix_eigenvalues_pdu_cd::make, py::arg("shape"),
                  py::arg("sort_by_magnitude") = true,
                  "Create matrix eigenvalues PDU block")

      .def(
          "set_sort_by_magnitude",
          [](matrix_eigenvalues_pdu_cd &self, bool sort) {
            self.set_sort_by_magnitude(sort);
          },
          "Set eigenvalue sorting mode")
      .def(
          "get_sort_by_magnitude",
          [](matrix_eigenvalues_pdu_cd &self) {
            return self.get_sort_by_magnitude();
          },
          "Get eigenvalue sorting mode");
}