/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_sqrt.h) */
/* BINDTOOL_HEADER_FILE_HASH(3f8047f8c9874a95a2a2afffa2a65d20) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_sqrt.h>
// pydoc.h is automatically generated in the build directory
// #include <matrix_sqrt_pydoc.h>  // Disabled until auto-generated

void bind_matrix_sqrt(py::module &m) {

  // Sync bindings for all precision variants
  using matrix_sqrt_sync_f = gr::linalg::matrix_sqrt_sync_f;
  using matrix_sqrt_sync_d = gr::linalg::matrix_sqrt_sync_d;
  using matrix_sqrt_sync_c = gr::linalg::matrix_sqrt_sync_cf;
  using matrix_sqrt_sync_cd = gr::linalg::matrix_sqrt_sync_cd;

  py::class_<matrix_sqrt_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_sqrt_sync_f>>(
      m, "matrix_sqrt_sync_f", "Matrix square root sync block (float)")

      .def_static("make", &matrix_sqrt_sync_f::make,
                  "Create matrix square root sync block");

  py::class_<matrix_sqrt_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_sqrt_sync_d>>(
      m, "matrix_sqrt_sync_d", "Matrix square root sync block (double)")

      .def_static("make", &matrix_sqrt_sync_d::make,
                  "Create matrix square root sync block");

  py::class_<matrix_sqrt_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_sqrt_sync_c>>(
      m, "matrix_sqrt_sync_c", "Matrix square root sync block (complex float)")

      .def_static("make", &matrix_sqrt_sync_c::make,
                  "Create matrix square root sync block");

  py::class_<matrix_sqrt_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_sqrt_sync_cd>>(
      m, "matrix_sqrt_sync_cd",
      "Matrix square root sync block (complex double)")

      .def_static("make", &matrix_sqrt_sync_cd::make,
                  "Create matrix square root sync block");

  // PDU bindings for all precision variants
  using matrix_sqrt_pdu_f = gr::linalg::matrix_sqrt_pdu_f;
  using matrix_sqrt_pdu_d = gr::linalg::matrix_sqrt_pdu_d;
  using matrix_sqrt_pdu_c = gr::linalg::matrix_sqrt_pdu_cf;
  using matrix_sqrt_pdu_cd = gr::linalg::matrix_sqrt_pdu_cd;

  py::class_<matrix_sqrt_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<matrix_sqrt_pdu_f>>(
      m, "matrix_sqrt_pdu_f", "Matrix square root PDU block (float)")

      .def_static("make", &matrix_sqrt_pdu_f::make,
                  "Create matrix square root PDU block");

  py::class_<matrix_sqrt_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<matrix_sqrt_pdu_d>>(
      m, "matrix_sqrt_pdu_d", "Matrix square root PDU block (double)")

      .def_static("make", &matrix_sqrt_pdu_d::make,
                  "Create matrix square root PDU block");

  py::class_<matrix_sqrt_pdu_c, gr::block, gr::basic_block,
             std::shared_ptr<matrix_sqrt_pdu_c>>(
      m, "matrix_sqrt_pdu_c", "Matrix square root PDU block (complex float)")

      .def_static("make", &matrix_sqrt_pdu_c::make,
                  "Create matrix square root PDU block");

  py::class_<matrix_sqrt_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<matrix_sqrt_pdu_cd>>(
      m, "matrix_sqrt_pdu_cd", "Matrix square root PDU block (complex double)")

      .def_static("make", &matrix_sqrt_pdu_cd::make,
                  "Create matrix square root PDU block");
}