/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_hermitian.h) */
/* BINDTOOL_HEADER_FILE_HASH(9727552dc6df8b849e11df21ae5193ba) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_hermitian.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_hermitian_pydoc.h>

void bind_matrix_hermitian(py::module &m) {
  using matrix_hermitian_sync_f = ::gr::linalg::matrix_hermitian_sync<float>;
  using matrix_hermitian_sync_d = ::gr::linalg::matrix_hermitian_sync<double>;
  using matrix_hermitian_sync_cf =
      ::gr::linalg::matrix_hermitian_sync<gr_complex>;
  using matrix_hermitian_sync_cd =
      ::gr::linalg::matrix_hermitian_sync<std::complex<double>>;

  py::class_<matrix_hermitian_sync_f, gr::sync_block,
             std::shared_ptr<matrix_hermitian_sync_f>>(
      m, "matrix_hermitian_sync_f", D(matrix_hermitian))

      .def(py::init(&matrix_hermitian_sync_f::make), py::arg("shape"),
           D(matrix_hermitian, make));

  py::class_<matrix_hermitian_sync_d, gr::sync_block,
             std::shared_ptr<matrix_hermitian_sync_d>>(
      m, "matrix_hermitian_sync_d", D(matrix_hermitian))

      .def(py::init(&matrix_hermitian_sync_d::make), py::arg("shape"),
           D(matrix_hermitian, make));

  py::class_<matrix_hermitian_sync_cf, gr::sync_block,
             std::shared_ptr<matrix_hermitian_sync_cf>>(
      m, "matrix_hermitian_sync_cf", D(matrix_hermitian))

      .def(py::init(&matrix_hermitian_sync_cf::make), py::arg("shape"),
           D(matrix_hermitian, make));

  py::class_<matrix_hermitian_sync_cd, gr::sync_block,
             std::shared_ptr<matrix_hermitian_sync_cd>>(
      m, "matrix_hermitian_sync_cd", D(matrix_hermitian))

      .def(py::init(&matrix_hermitian_sync_cd::make), py::arg("shape"),
           D(matrix_hermitian, make));
}