/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_condition_number.h) */
/* BINDTOOL_HEADER_FILE_HASH(9b7be0a546e2bcec993092ca71bc0380) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_condition_number.h>
// pydoc.h is automatically generated in the build directory
#include <matrix_condition_number_pydoc.h>

void bind_matrix_condition_number(py::module &m) {

  using matrix_condition_number_sync_f =
      gr::linalg::matrix_condition_number_sync<float>;
  using matrix_condition_number_sync_d =
      gr::linalg::matrix_condition_number_sync<double>;
  using matrix_condition_number_sync_cf =
      gr::linalg::matrix_condition_number_sync<std::complex<float>>;
  using matrix_condition_number_sync_cd =
      gr::linalg::matrix_condition_number_sync<std::complex<double>>;

  py::class_<matrix_condition_number_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_condition_number_sync_f>>(
      m, "matrix_condition_number_sync_f", D(matrix_condition_number_sync))

      .def(py::init(&matrix_condition_number_sync_f::make), py::arg("shape"),
           D(matrix_condition_number_sync, make))
      .def_static("make", &matrix_condition_number_sync_f::make,
                  py::arg("shape"), D(matrix_condition_number_sync, make));

  py::class_<matrix_condition_number_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_condition_number_sync_d>>(
      m, "matrix_condition_number_sync_d", D(matrix_condition_number_sync))

      .def(py::init(&matrix_condition_number_sync_d::make), py::arg("shape"),
           D(matrix_condition_number_sync, make))
      .def_static("make", &matrix_condition_number_sync_d::make,
                  py::arg("shape"), D(matrix_condition_number_sync, make));

  py::class_<matrix_condition_number_sync_cf, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_condition_number_sync_cf>>(
      m, "matrix_condition_number_sync_cf", D(matrix_condition_number_sync))

      .def(py::init(&matrix_condition_number_sync_cf::make), py::arg("shape"),
           D(matrix_condition_number_sync, make))
      .def_static("make", &matrix_condition_number_sync_cf::make,
                  py::arg("shape"), D(matrix_condition_number_sync, make));

  py::class_<matrix_condition_number_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<matrix_condition_number_sync_cd>>(
      m, "matrix_condition_number_sync_cd", D(matrix_condition_number_sync))

      .def(py::init(&matrix_condition_number_sync_cd::make), py::arg("shape"),
           D(matrix_condition_number_sync, make))
      .def_static("make", &matrix_condition_number_sync_cd::make,
                  py::arg("shape"), D(matrix_condition_number_sync, make));
}