/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(matrix_norm.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0672a1a4f548929800f6c1b6f174fde6) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/matrix_norm.h>
#include <gnuradio/linalg/types.h>

using namespace gr::linalg;
// pydoc.h is automatically generated in the build directory
#include <matrix_norm_pydoc.h>

void bind_matrix_norm(py::module &m) {

  using matrix_norm_sync_f = gr::linalg::matrix_norm_sync_f;
  using matrix_norm_sync_d = gr::linalg::matrix_norm_sync_d;
  using matrix_norm_sync_c = gr::linalg::matrix_norm_sync_c;
  using matrix_norm_sync_cd = gr::linalg::matrix_norm_sync_cd;
  using norm_type = gr::linalg::norm_type;

  // Bind the norm_type enum
  py::enum_<norm_type>(m, "norm_type")
      .value("L1", norm_type::L1)
      .value("L2", norm_type::L2)
      .value("Frobenius", norm_type::Frobenius)
      .value("Max", norm_type::Max)
      .export_values();

  py::class_<matrix_norm_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_norm_sync_f>>(m, "matrix_norm_sync_f",
                                                  D(matrix_norm))

      .def(py::init([](const types::shape &shape, norm_type norm) {
             return matrix_norm_sync_f::make(shape, norm);
           }),
           py::arg("shape"), py::arg("norm") = norm_type::Frobenius)
      .def_static(
          "make",
          [](const types::shape &shape, norm_type norm) {
            return matrix_norm_sync_f::make(shape, norm);
          },
          py::arg("shape"), py::arg("norm") = norm_type::Frobenius);

  py::class_<matrix_norm_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_norm_sync_d>>(m, "matrix_norm_sync_d",
                                                  D(matrix_norm))

      .def(py::init([](const types::shape &shape, norm_type norm) {
             return matrix_norm_sync_d::make(shape, norm);
           }),
           py::arg("shape"), py::arg("norm") = norm_type::Frobenius)
      .def_static(
          "make",
          [](const types::shape &shape, norm_type norm) {
            return matrix_norm_sync_d::make(shape, norm);
          },
          py::arg("shape"), py::arg("norm") = norm_type::Frobenius);

  py::class_<matrix_norm_sync_c, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_norm_sync_c>>(m, "matrix_norm_sync_c",
                                                  D(matrix_norm))

      .def(py::init([](const types::shape &shape, norm_type norm) {
             return matrix_norm_sync_c::make(shape, norm);
           }),
           py::arg("shape"), py::arg("norm") = norm_type::Frobenius)
      .def_static(
          "make",
          [](const types::shape &shape, norm_type norm) {
            return matrix_norm_sync_c::make(shape, norm);
          },
          py::arg("shape"), py::arg("norm") = norm_type::Frobenius);

  py::class_<matrix_norm_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<matrix_norm_sync_cd>>(m, "matrix_norm_sync_cd",
                                                   D(matrix_norm))

      .def(py::init([](const types::shape &shape, norm_type norm) {
             return matrix_norm_sync_cd::make(shape, norm);
           }),
           py::arg("shape"), py::arg("norm") = norm_type::Frobenius)
      .def_static(
          "make",
          [](const types::shape &shape, norm_type norm) {
            return matrix_norm_sync_cd::make(shape, norm);
          },
          py::arg("shape"), py::arg("norm") = norm_type::Frobenius);
}