/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(ones.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3c44b4b7e10033590e663d5188dfd38c) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/ones.h>
// pydoc.h is automatically generated in the build directory
#include <ones_pydoc.h>

void bind_ones(py::module &m) {

  using ones_sync_f = gr::linalg::ones<float>;
  using ones_sync_d = gr::linalg::ones<double>;
  using ones_sync_cf = gr::linalg::ones<std::complex<float>>;
  using ones_sync_cd = gr::linalg::ones<std::complex<double>>;

  py::class_<ones_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<ones_sync_f>>(m, "ones_sync_f", D(ones))

      .def(py::init(&ones_sync_f::make), py::arg("shape"), D(ones, make))
      .def_static("make", &ones_sync_f::make, py::arg("shape"), D(ones, make));

  py::class_<ones_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<ones_sync_d>>(m, "ones_sync_d", D(ones))

      .def(py::init(&ones_sync_d::make), py::arg("shape"), D(ones, make))
      .def_static("make", &ones_sync_d::make, py::arg("shape"), D(ones, make));

  py::class_<ones_sync_cf, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<ones_sync_cf>>(m, "ones_sync_cf", D(ones))

      .def(py::init(&ones_sync_cf::make), py::arg("shape"), D(ones, make))
      .def_static("make", &ones_sync_cf::make, py::arg("shape"), D(ones, make));

  py::class_<ones_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<ones_sync_cd>>(m, "ones_sync_cd", D(ones))

      .def(py::init(&ones_sync_cd::make), py::arg("shape"), D(ones, make))
      .def_static("make", &ones_sync_cd::make, py::arg("shape"), D(ones, make));
}
