/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(solve_triangular.h) */
/* BINDTOOL_HEADER_FILE_HASH(ea381ae981e189abbdbdbe4a1c888a19) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/solve_triangular.h>
// pydoc.h is automatically generated in the build directory
#include <solve_triangular_pydoc.h>

void bind_solve_triangular(py::module &m) {

  // Bind a common TriangularType enum for user convenience
  py::enum_<gr::linalg::solve_triangular<float>::triangular_type>(
      m, "TriangularType")
      .value("LOWER",
             gr::linalg::solve_triangular<float>::triangular_type::LOWER)
      .value("UPPER",
             gr::linalg::solve_triangular<float>::triangular_type::UPPER)
      .export_values();

  py::enum_<gr::linalg::solve_triangular<double>::triangular_type>(
      m, "triangular_type_d")
      .value("LOWER",
             gr::linalg::solve_triangular<double>::triangular_type::LOWER)
      .value("UPPER",
             gr::linalg::solve_triangular<double>::triangular_type::UPPER)
      .export_values();

  py::enum_<gr::linalg::solve_triangular<std::complex<float>>::triangular_type>(
      m, "triangular_type_cf")
      .value("LOWER", gr::linalg::solve_triangular<
                          std::complex<float>>::triangular_type::LOWER)
      .value("UPPER", gr::linalg::solve_triangular<
                          std::complex<float>>::triangular_type::UPPER)
      .export_values();

  py::enum_<
      gr::linalg::solve_triangular<std::complex<double>>::triangular_type>(
      m, "triangular_type_cd")
      .value("LOWER", gr::linalg::solve_triangular<
                          std::complex<double>>::triangular_type::LOWER)
      .value("UPPER", gr::linalg::solve_triangular<
                          std::complex<double>>::triangular_type::UPPER)
      .export_values();

  // Bind sync blocks for all precision types
  using solve_triangular_sync_f = gr::linalg::solve_triangular_sync<float>;
  using solve_triangular_sync_d = gr::linalg::solve_triangular_sync<double>;
  using solve_triangular_sync_cf =
      gr::linalg::solve_triangular_sync<std::complex<float>>;
  using solve_triangular_sync_cd =
      gr::linalg::solve_triangular_sync<std::complex<double>>;

  py::class_<solve_triangular_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_triangular_sync_f>>(
      m, "solve_triangular_sync_f")
      .def_static("make", &solve_triangular_sync_f::make,
                  py::arg("shape_matrix"), py::arg("shape_rhs"),
                  py::arg("tri_type"), py::arg("unit_diagonal"));

  py::class_<solve_triangular_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_triangular_sync_d>>(
      m, "solve_triangular_sync_d")
      .def_static("make", &solve_triangular_sync_d::make,
                  py::arg("shape_matrix"), py::arg("shape_rhs"),
                  py::arg("tri_type"), py::arg("unit_diagonal"));

  py::class_<solve_triangular_sync_cf, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_triangular_sync_cf>>(
      m, "solve_triangular_sync_cf")
      .def_static("make", &solve_triangular_sync_cf::make,
                  py::arg("shape_matrix"), py::arg("shape_rhs"),
                  py::arg("tri_type"), py::arg("unit_diagonal"));

  py::class_<solve_triangular_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_triangular_sync_cd>>(
      m, "solve_triangular_sync_cd")
      .def_static("make", &solve_triangular_sync_cd::make,
                  py::arg("shape_matrix"), py::arg("shape_rhs"),
                  py::arg("tri_type"), py::arg("unit_diagonal"));

  // Bind PDU blocks for all precision types
  using solve_triangular_pdu_f = gr::linalg::solve_triangular_pdu<float>;
  using solve_triangular_pdu_d = gr::linalg::solve_triangular_pdu<double>;
  using solve_triangular_pdu_cf =
      gr::linalg::solve_triangular_pdu<std::complex<float>>;
  using solve_triangular_pdu_cd =
      gr::linalg::solve_triangular_pdu<std::complex<double>>;

  py::class_<solve_triangular_pdu_f, gr::basic_block,
             std::shared_ptr<solve_triangular_pdu_f>>(m,
                                                      "solve_triangular_pdu_f")
      .def_static("make", &solve_triangular_pdu_f::make,
                  py::arg("shape_matrix"), py::arg("shape_rhs"),
                  py::arg("tri_type"), py::arg("unit_diagonal"));

  py::class_<solve_triangular_pdu_d, gr::basic_block,
             std::shared_ptr<solve_triangular_pdu_d>>(m,
                                                      "solve_triangular_pdu_d")
      .def_static("make", &solve_triangular_pdu_d::make,
                  py::arg("shape_matrix"), py::arg("shape_rhs"),
                  py::arg("tri_type"), py::arg("unit_diagonal"));

  py::class_<solve_triangular_pdu_cf, gr::basic_block,
             std::shared_ptr<solve_triangular_pdu_cf>>(
      m, "solve_triangular_pdu_cf")
      .def_static("make", &solve_triangular_pdu_cf::make,
                  py::arg("shape_matrix"), py::arg("shape_rhs"),
                  py::arg("tri_type"), py::arg("unit_diagonal"));

  py::class_<solve_triangular_pdu_cd, gr::basic_block,
             std::shared_ptr<solve_triangular_pdu_cd>>(
      m, "solve_triangular_pdu_cd")
      .def_static("make", &solve_triangular_pdu_cd::make,
                  py::arg("shape_matrix"), py::arg("shape_rhs"),
                  py::arg("tri_type"), py::arg("unit_diagonal"));
}
