/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(solve_iterative.h) */
/* BINDTOOL_HEADER_FILE_HASH(591b687316178ef6c75314edfa2491a8) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/solve_iterative.h>
// pydoc.h is automatically generated in the build directory
// #include <solve_iterative_pydoc.h>  // Temporarily commented out until
// docstring generation is fixed

void bind_solve_iterative(py::module &m) {
  using namespace gr::linalg;

  // Bind the iterative_method enum
  py::enum_<iterative_method>(m, "iterative_method",
                              "Iterative solver methods enumeration")
      .value("AUTO", iterative_method::AUTO,
             "Automatic method selection based on matrix properties")
      .value("CG", iterative_method::CG,
             "Conjugate Gradient (for symmetric positive definite)")
      .value("BICGSTAB", iterative_method::BICGSTAB,
             "Biconjugate Gradient Stabilized (general matrices)")
      .value("GMRES", iterative_method::GMRES,
             "Generalized Minimal Residual (general matrices)")
      .value("LSCG", iterative_method::LSCG,
             "Least Squares Conjugate Gradient (rectangular matrices)")
      .export_values();

  // Bind the iterative solver sync block for float
  py::class_<solve_iterative_sync<float>, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_iterative_sync<float>>>(
      m, "solve_iterative_sync_f",
      "Iterative linear system solver for float precision")
      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             iterative_method method = iterative_method::AUTO,
             int max_iterations = 1000, float tolerance = 1e-6f,
             bool use_initial_guess = false) {
            return solve_iterative_sync<float>::make(
                shape_a, shape_b, method, max_iterations, tolerance,
                use_initial_guess, nullptr);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = iterative_method::AUTO,
          py::arg("max_iterations") = 1000, py::arg("tolerance") = 1e-6f,
          py::arg("use_initial_guess") = false,
          "Create iterative linear system solver");

  // Bind the iterative solver sync block for double
  py::class_<solve_iterative_sync<double>, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_iterative_sync<double>>>(
      m, "solve_iterative_sync_d",
      "Iterative linear system solver for double precision")
      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             iterative_method method = iterative_method::AUTO,
             int max_iterations = 1000, double tolerance = 1e-6,
             bool use_initial_guess = false) {
            return solve_iterative_sync<double>::make(
                shape_a, shape_b, method, max_iterations, tolerance,
                use_initial_guess, nullptr);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = iterative_method::AUTO,
          py::arg("max_iterations") = 1000, py::arg("tolerance") = 1e-6,
          py::arg("use_initial_guess") = false,
          "Create iterative linear system solver");

  // Bind the iterative solver sync block for complex<float>
  py::class_<solve_iterative_sync<std::complex<float>>, gr::sync_block,
             gr::block, gr::basic_block,
             std::shared_ptr<solve_iterative_sync<std::complex<float>>>>(
      m, "solve_iterative_sync_cf",
      "Iterative linear system solver for complex float precision")
      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             iterative_method method = iterative_method::AUTO,
             int max_iterations = 1000, float tolerance = 1e-6f,
             bool use_initial_guess = false) {
            return solve_iterative_sync<std::complex<float>>::make(
                shape_a, shape_b, method, max_iterations, tolerance,
                use_initial_guess, nullptr);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = iterative_method::AUTO,
          py::arg("max_iterations") = 1000, py::arg("tolerance") = 1e-6f,
          py::arg("use_initial_guess") = false,
          "Create iterative linear system solver");

  // Bind the iterative solver sync block for complex<double>
  py::class_<solve_iterative_sync<std::complex<double>>, gr::sync_block,
             gr::block, gr::basic_block,
             std::shared_ptr<solve_iterative_sync<std::complex<double>>>>(
      m, "solve_iterative_sync_cd",
      "Iterative linear system solver for complex double precision")
      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             iterative_method method = iterative_method::AUTO,
             int max_iterations = 1000, double tolerance = 1e-6,
             bool use_initial_guess = false) {
            return solve_iterative_sync<std::complex<double>>::make(
                shape_a, shape_b, method, max_iterations, tolerance,
                use_initial_guess, nullptr);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = iterative_method::AUTO,
          py::arg("max_iterations") = 1000, py::arg("tolerance") = 1e-6,
          py::arg("use_initial_guess") = false,
          "Create iterative linear system solver");

  // Bind the iterative solver PDU block for float
  py::class_<solve_iterative_pdu<float>, gr::block, gr::basic_block,
             std::shared_ptr<solve_iterative_pdu<float>>>(
      m, "solve_iterative_pdu_f",
      "Iterative linear system solver PDU block for float precision")
      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             iterative_method method = iterative_method::AUTO,
             int max_iterations = 1000, float tolerance = 1e-6f,
             bool use_initial_guess = false) {
            return solve_iterative_pdu<float>::make(shape_a, shape_b, method,
                                                    max_iterations, tolerance,
                                                    use_initial_guess, nullptr);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = iterative_method::AUTO,
          py::arg("max_iterations") = 1000, py::arg("tolerance") = 1e-6f,
          py::arg("use_initial_guess") = false,
          "Create iterative linear system solver PDU block");

  // Bind the iterative solver PDU block for double
  py::class_<solve_iterative_pdu<double>, gr::block, gr::basic_block,
             std::shared_ptr<solve_iterative_pdu<double>>>(
      m, "solve_iterative_pdu_d",
      "Iterative linear system solver PDU block for double precision")
      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             iterative_method method = iterative_method::AUTO,
             int max_iterations = 1000, double tolerance = 1e-6,
             bool use_initial_guess = false) {
            return solve_iterative_pdu<double>::make(
                shape_a, shape_b, method, max_iterations, tolerance,
                use_initial_guess, nullptr);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = iterative_method::AUTO,
          py::arg("max_iterations") = 1000, py::arg("tolerance") = 1e-6,
          py::arg("use_initial_guess") = false,
          "Create iterative linear system solver PDU block");

  // Bind the iterative solver PDU block for complex<float>
  py::class_<solve_iterative_pdu<std::complex<float>>, gr::block,
             gr::basic_block,
             std::shared_ptr<solve_iterative_pdu<std::complex<float>>>>(
      m, "solve_iterative_pdu_cf",
      "Iterative linear system solver PDU block for complex float precision")
      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             iterative_method method = iterative_method::AUTO,
             int max_iterations = 1000, float tolerance = 1e-6f,
             bool use_initial_guess = false) {
            return solve_iterative_pdu<std::complex<float>>::make(
                shape_a, shape_b, method, max_iterations, tolerance,
                use_initial_guess, nullptr);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = iterative_method::AUTO,
          py::arg("max_iterations") = 1000, py::arg("tolerance") = 1e-6f,
          py::arg("use_initial_guess") = false,
          "Create iterative linear system solver PDU block");

  // Bind the iterative solver PDU block for complex<double>
  py::class_<solve_iterative_pdu<std::complex<double>>, gr::block,
             gr::basic_block,
             std::shared_ptr<solve_iterative_pdu<std::complex<double>>>>(
      m, "solve_iterative_pdu_cd",
      "Iterative linear system solver PDU block for complex double precision")
      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             iterative_method method = iterative_method::AUTO,
             int max_iterations = 1000, double tolerance = 1e-6,
             bool use_initial_guess = false) {
            return solve_iterative_pdu<std::complex<double>>::make(
                shape_a, shape_b, method, max_iterations, tolerance,
                use_initial_guess, nullptr);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = iterative_method::AUTO,
          py::arg("max_iterations") = 1000, py::arg("tolerance") = 1e-6,
          py::arg("use_initial_guess") = false,
          "Create iterative linear system solver PDU block");
}