/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(solve_least_squares.h) */
/* BINDTOOL_HEADER_FILE_HASH(97afab21f59ee10193fe3bc7584f1375) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/solve_least_squares.h>
// pydoc.h is automatically generated in the build directory
// #include <solve_least_squares_pydoc.h>  // Disabled until auto-generated

void bind_solve_least_squares(py::module &m) {

  // Bind the least_squares_method enum
  py::enum_<gr::linalg::least_squares_method>(
      m, "least_squares_method", "Method selection for least squares solver")
      .value("AUTO", gr::linalg::least_squares_method::AUTO,
             "Automatic selection based on condition number")
      .value("NORMAL_EQ", gr::linalg::least_squares_method::NORMAL_EQ,
             "Normal equations: (A^T A) x = A^T b")
      .value("QR", gr::linalg::least_squares_method::QR,
             "QR decomposition method")
      .value("SVD", gr::linalg::least_squares_method::SVD,
             "Singular Value Decomposition (most robust)");

  // Sync bindings for all precision variants
  using solve_least_squares_sync_f = gr::linalg::solve_least_squares_sync_f;
  using solve_least_squares_sync_d = gr::linalg::solve_least_squares_sync_d;
  using solve_least_squares_sync_c = gr::linalg::solve_least_squares_sync_c;
  using solve_least_squares_sync_cd = gr::linalg::solve_least_squares_sync_cd;

  py::class_<solve_least_squares_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_least_squares_sync_f>>(
      m, "solve_least_squares_sync_f", "Solve least squares sync block (float)")

      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             gr::linalg::least_squares_method method, double tolerance) {
            return solve_least_squares_sync_f::make(shape_a, shape_b, method,
                                                    tolerance);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = gr::linalg::least_squares_method::AUTO,
          py::arg("tolerance") = 1e-10,
          "Create solve least squares sync block");

  py::class_<solve_least_squares_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_least_squares_sync_d>>(
      m, "solve_least_squares_sync_d",
      "Solve least squares sync block (double)")

      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             gr::linalg::least_squares_method method, double tolerance) {
            return solve_least_squares_sync_d::make(shape_a, shape_b, method,
                                                    tolerance);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = gr::linalg::least_squares_method::AUTO,
          py::arg("tolerance") = 1e-10,
          "Create solve least squares sync block");

  py::class_<solve_least_squares_sync_c, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_least_squares_sync_c>>(
      m, "solve_least_squares_sync_c",
      "Solve least squares sync block (complex float)")

      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             gr::linalg::least_squares_method method, double tolerance) {
            return solve_least_squares_sync_c::make(shape_a, shape_b, method,
                                                    tolerance);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = gr::linalg::least_squares_method::AUTO,
          py::arg("tolerance") = 1e-10,
          "Create solve least squares sync block");

  py::class_<solve_least_squares_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<solve_least_squares_sync_cd>>(
      m, "solve_least_squares_sync_cd",
      "Solve least squares sync block (complex double)")

      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             gr::linalg::least_squares_method method, double tolerance) {
            return solve_least_squares_sync_cd::make(shape_a, shape_b, method,
                                                     tolerance);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = gr::linalg::least_squares_method::AUTO,
          py::arg("tolerance") = 1e-10,
          "Create solve least squares sync block");

  // PDU bindings for all precision variants
  using solve_least_squares_pdu_f = gr::linalg::solve_least_squares_pdu_f;
  using solve_least_squares_pdu_d = gr::linalg::solve_least_squares_pdu_d;
  using solve_least_squares_pdu_c = gr::linalg::solve_least_squares_pdu_c;
  using solve_least_squares_pdu_cd = gr::linalg::solve_least_squares_pdu_cd;

  py::class_<solve_least_squares_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<solve_least_squares_pdu_f>>(
      m, "solve_least_squares_pdu_f", "Solve least squares PDU block (float)")

      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             gr::linalg::least_squares_method method, double tolerance) {
            return solve_least_squares_pdu_f::make(shape_a, shape_b, method,
                                                   tolerance);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = gr::linalg::least_squares_method::AUTO,
          py::arg("tolerance") = 1e-10, "Create solve least squares PDU block");

  py::class_<solve_least_squares_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<solve_least_squares_pdu_d>>(
      m, "solve_least_squares_pdu_d", "Solve least squares PDU block (double)")

      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             gr::linalg::least_squares_method method, double tolerance) {
            return solve_least_squares_pdu_d::make(shape_a, shape_b, method,
                                                   tolerance);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = gr::linalg::least_squares_method::AUTO,
          py::arg("tolerance") = 1e-10, "Create solve least squares PDU block");

  py::class_<solve_least_squares_pdu_c, gr::block, gr::basic_block,
             std::shared_ptr<solve_least_squares_pdu_c>>(
      m, "solve_least_squares_pdu_c",
      "Solve least squares PDU block (complex float)")

      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             gr::linalg::least_squares_method method, double tolerance) {
            return solve_least_squares_pdu_c::make(shape_a, shape_b, method,
                                                   tolerance);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = gr::linalg::least_squares_method::AUTO,
          py::arg("tolerance") = 1e-10, "Create solve least squares PDU block");

  py::class_<solve_least_squares_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<solve_least_squares_pdu_cd>>(
      m, "solve_least_squares_pdu_cd",
      "Solve least squares PDU block (complex double)")

      .def_static(
          "make",
          [](const std::vector<int> &shape_a, const std::vector<int> &shape_b,
             gr::linalg::least_squares_method method, double tolerance) {
            return solve_least_squares_pdu_cd::make(shape_a, shape_b, method,
                                                    tolerance);
          },
          py::arg("shape_a"), py::arg("shape_b"),
          py::arg("method") = gr::linalg::least_squares_method::AUTO,
          py::arg("tolerance") = 1e-10, "Create solve least squares PDU block");
}
