/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_normalize.h) */
/* BINDTOOL_HEADER_FILE_HASH(6049e72677d1444aa62b895f1e06cd3b) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/types.h>
#include <gnuradio/linalg/vector_normalize.h>
// pydoc.h is automatically generated in the build directory
#include <vector_normalize_pydoc.h>

using namespace gr::linalg;

void bind_vector_normalize(py::module &m) {

  using vector_normalize_sync_f = gr::linalg::vector_normalize_sync_f;
  using vector_normalize_sync_d = gr::linalg::vector_normalize_sync_d;
  using vector_normalize_sync_c = gr::linalg::vector_normalize_sync_c;
  using vector_normalize_sync_cd = gr::linalg::vector_normalize_sync_cd;

  py::class_<vector_normalize_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_normalize_sync_f>>(
      m, "vector_normalize_sync_f", D(vector_normalize))

      .def(py::init([](const types::shape &shape, int order) {
             return vector_normalize_sync_f::make(shape, order);
           }),
           py::arg("shape"), py::arg("order") = 2)
      .def_static(
          "make",
          [](const types::shape &shape, int order) {
            return vector_normalize_sync_f::make(shape, order);
          },
          py::arg("shape"), py::arg("order") = 2);

  py::class_<vector_normalize_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_normalize_sync_d>>(
      m, "vector_normalize_sync_d", D(vector_normalize))

      .def(py::init([](const types::shape &shape, int order) {
             return vector_normalize_sync_d::make(shape, order);
           }),
           py::arg("shape"), py::arg("order") = 2)
      .def_static(
          "make",
          [](const types::shape &shape, int order) {
            return vector_normalize_sync_d::make(shape, order);
          },
          py::arg("shape"), py::arg("order") = 2);

  py::class_<vector_normalize_sync_c, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_normalize_sync_c>>(
      m, "vector_normalize_sync_c", D(vector_normalize))

      .def(py::init([](const types::shape &shape, int order) {
             return vector_normalize_sync_c::make(shape, order);
           }),
           py::arg("shape"), py::arg("order") = 2)
      .def_static(
          "make",
          [](const types::shape &shape, int order) {
            return vector_normalize_sync_c::make(shape, order);
          },
          py::arg("shape"), py::arg("order") = 2);

  py::class_<vector_normalize_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_normalize_sync_cd>>(
      m, "vector_normalize_sync_cd", D(vector_normalize))

      .def(py::init([](const types::shape &shape, int order) {
             return vector_normalize_sync_cd::make(shape, order);
           }),
           py::arg("shape"), py::arg("order") = 2)
      .def_static(
          "make",
          [](const types::shape &shape, int order) {
            return vector_normalize_sync_cd::make(shape, order);
          },
          py::arg("shape"), py::arg("order") = 2);
}
