/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_cross_product.h) */
/* BINDTOOL_HEADER_FILE_HASH(225d947995630dadbbb8dfbc9405139c)             */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/vector_cross_product.h>
// pydoc.h is automatically generated in the build directory
#include <vector_cross_product_pydoc.h>

void bind_vector_cross_product(py::module &m) {

  using vector_cross_product_sync =
      gr::linalg::vector_cross_product_sync<float>;
  using vector_cross_product_sync_d =
      gr::linalg::vector_cross_product_sync<double>;
  using vector_cross_product_sync_cf =
      gr::linalg::vector_cross_product_sync<std::complex<float>>;
  using vector_cross_product_sync_cd =
      gr::linalg::vector_cross_product_sync<std::complex<double>>;

  py::class_<vector_cross_product_sync, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_cross_product_sync>>(
      m, "vector_cross_product_sync_f",
      "Vector cross product sync block for float")

      .def(py::init(&vector_cross_product_sync::make),
           py::arg("validate_3d") = true,
           "Create vector cross product sync block");

  py::class_<vector_cross_product_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_cross_product_sync_d>>(
      m, "vector_cross_product_sync_d",
      "Vector cross product sync block for double")

      .def(py::init(&vector_cross_product_sync_d::make),
           py::arg("validate_3d") = true,
           "Create vector cross product sync block");

  py::class_<vector_cross_product_sync_cf, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_cross_product_sync_cf>>(
      m, "vector_cross_product_sync_cf",
      "Vector cross product sync block for complex float")

      .def(py::init(&vector_cross_product_sync_cf::make),
           py::arg("validate_3d") = true,
           "Create vector cross product sync block");

  py::class_<vector_cross_product_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_cross_product_sync_cd>>(
      m, "vector_cross_product_sync_cd",
      "Vector cross product sync block for complex double")

      .def(py::init(&vector_cross_product_sync_cd::make),
           py::arg("validate_3d") = true,
           "Create vector cross product sync block");
}