/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Vector Projection Python Bindings Status:
 * - Real-valued bindings (float, double): FULLY FUNCTIONAL
 * - Complex bindings (complex float/double): BOUND BUT ISSUE IN C++ BACKEND
 *   The complex variants are properly bound but the underlying C++
 * implementation has a known issue with complex conjugate dot products
 * returning zero.
 *   TODO: Fix complex projection math in vector_projection_impl.cc
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_projection.h) */
/* BINDTOOL_HEADER_FILE_HASH(a3b69722a1ad2abd113279fb9c09f784) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/vector_projection.h>
// pydoc.h is automatically generated in the build directory
// #include <vector_projection_pydoc.h>  // Disabled until auto-generated

void bind_vector_projection(py::module &m) {

  // Sync bindings for all precision variants
  using vector_projection_sync_f = gr::linalg::vector_projection_sync_f;
  using vector_projection_sync_d = gr::linalg::vector_projection_sync_d;
  using vector_projection_sync_c = gr::linalg::vector_projection_sync_c;
  using vector_projection_sync_cd = gr::linalg::vector_projection_sync_cd;

  py::class_<vector_projection_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_projection_sync_f>>(
      m, "vector_projection_sync_f", "Vector projection sync block (float)")

      .def_static("make", &vector_projection_sync_f::make, py::arg("shape_a"),
                  py::arg("shape_b"), "Create vector projection sync block");

  py::class_<vector_projection_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_projection_sync_d>>(
      m, "vector_projection_sync_d", "Vector projection sync block (double)")

      .def_static("make", &vector_projection_sync_d::make, py::arg("shape_a"),
                  py::arg("shape_b"), "Create vector projection sync block");

  py::class_<vector_projection_sync_c, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_projection_sync_c>>(
      m, "vector_projection_sync_c",
      "Vector projection sync block (complex float)")

      .def_static("make", &vector_projection_sync_c::make, py::arg("shape_a"),
                  py::arg("shape_b"), "Create vector projection sync block");

  py::class_<vector_projection_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_projection_sync_cd>>(
      m, "vector_projection_sync_cd",
      "Vector projection sync block (complex double)")

      .def_static("make", &vector_projection_sync_cd::make, py::arg("shape_a"),
                  py::arg("shape_b"), "Create vector projection sync block");

  // PDU bindings for all precision variants
  using vector_projection_pdu_f = gr::linalg::vector_projection_pdu_f;
  using vector_projection_pdu_d = gr::linalg::vector_projection_pdu_d;
  using vector_projection_pdu_c = gr::linalg::vector_projection_pdu_c;
  using vector_projection_pdu_cd = gr::linalg::vector_projection_pdu_cd;

  py::class_<vector_projection_pdu_f, gr::block, gr::basic_block,
             std::shared_ptr<vector_projection_pdu_f>>(
      m, "vector_projection_pdu_f", "Vector projection PDU block (float)")

      .def_static("make", &vector_projection_pdu_f::make, py::arg("shape_a"),
                  py::arg("shape_b"), "Create vector projection PDU block");

  py::class_<vector_projection_pdu_d, gr::block, gr::basic_block,
             std::shared_ptr<vector_projection_pdu_d>>(
      m, "vector_projection_pdu_d", "Vector projection PDU block (double)")

      .def_static("make", &vector_projection_pdu_d::make, py::arg("shape_a"),
                  py::arg("shape_b"), "Create vector projection PDU block");

  py::class_<vector_projection_pdu_c, gr::block, gr::basic_block,
             std::shared_ptr<vector_projection_pdu_c>>(
      m, "vector_projection_pdu_c",
      "Vector projection PDU block (complex float)")

      .def_static("make", &vector_projection_pdu_c::make, py::arg("shape_a"),
                  py::arg("shape_b"), "Create vector projection PDU block");

  py::class_<vector_projection_pdu_cd, gr::block, gr::basic_block,
             std::shared_ptr<vector_projection_pdu_cd>>(
      m, "vector_projection_pdu_cd",
      "Vector projection PDU block (complex double)")

      .def_static("make", &vector_projection_pdu_cd::make, py::arg("shape_a"),
                  py::arg("shape_b"), "Create vector projection PDU block");
}
