/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_outer_product.h) */
/* BINDTOOL_HEADER_FILE_HASH(69e68c4c3ad023af5696e86dcb1bc5fe) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/vector_outer_product.h>

void bind_vector_outer_product(py::module &m) {

  using vector_outer_product_sync =
      gr::linalg::vector_outer_product_sync<float>;
  using vector_outer_product_sync_d =
      gr::linalg::vector_outer_product_sync<double>;
  using vector_outer_product_sync_cf =
      gr::linalg::vector_outer_product_sync<std::complex<float>>;
  using vector_outer_product_sync_cd =
      gr::linalg::vector_outer_product_sync<std::complex<double>>;

  py::class_<vector_outer_product_sync, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_outer_product_sync>>(
      m, "vector_outer_product_sync_f",
      "Vector outer product sync block for float")

      .def_static("make", &vector_outer_product_sync::make,
                  "Create vector outer product sync block");

  py::class_<vector_outer_product_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_outer_product_sync_d>>(
      m, "vector_outer_product_sync_d",
      "Vector outer product sync block for double")

      .def_static("make", &vector_outer_product_sync_d::make,
                  "Create vector outer product sync block");

  py::class_<vector_outer_product_sync_cf, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_outer_product_sync_cf>>(
      m, "vector_outer_product_sync_cf",
      "Vector outer product sync block for complex float")

      .def_static("make", &vector_outer_product_sync_cf::make,
                  "Create vector outer product sync block");

  py::class_<vector_outer_product_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_outer_product_sync_cd>>(
      m, "vector_outer_product_sync_cd",
      "Vector outer product sync block for complex double")

      .def_static("make", &vector_outer_product_sync_cd::make,
                  "Create vector outer product sync block");
}