/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_correlate.h) */
/* BINDTOOL_HEADER_FILE_HASH(3f71c82674366927c3ea6e0f848e3ab4) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/vector_correlate.h>
// pydoc.h is automatically generated in the build directory
#include <vector_correlate_pydoc.h>

void bind_vector_correlate(py::module &m) {

  // Bind the CorrelateMode enum for all types using template-independent
  // namespace - use typedef to avoid template dependency issues
  using CorrelateMode = gr::linalg::vector_correlate<float>::CorrelateMode;
  py::enum_<CorrelateMode>(m, "CorrelateMode")
      .value("FULL", CorrelateMode::FULL)
      .value("VALID", CorrelateMode::VALID)
      .value("SAME", CorrelateMode::SAME)
      .export_values();

  // Bind sync blocks for all precision types
  using vector_correlate_sync_f = gr::linalg::vector_correlate_sync<float>;
  using vector_correlate_sync_d = gr::linalg::vector_correlate_sync<double>;
  using vector_correlate_sync_c =
      gr::linalg::vector_correlate_sync<std::complex<float>>;
  using vector_correlate_sync_cd =
      gr::linalg::vector_correlate_sync<std::complex<double>>;

  py::class_<vector_correlate_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_correlate_sync_f>>(
      m, "vector_correlate_sync_f")
      .def_static(
          "make",
          [](const gr::linalg::types::shape &shape_a,
             const gr::linalg::types::shape &shape_b,
             CorrelateMode mode = CorrelateMode::FULL, bool normalize = false) {
            return vector_correlate_sync_f::make(
                shape_a, shape_b,
                static_cast<vector_correlate_sync_f::CorrelateMode>(mode),
                normalize);
          },
          py::arg("input_shape_a"), py::arg("input_shape_b"),
          py::arg("mode") = CorrelateMode::FULL, py::arg("normalize") = false);

  py::class_<vector_correlate_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_correlate_sync_d>>(
      m, "vector_correlate_sync_d")
      .def_static(
          "make",
          [](const gr::linalg::types::shape &shape_a,
             const gr::linalg::types::shape &shape_b,
             CorrelateMode mode = CorrelateMode::FULL, bool normalize = false) {
            return vector_correlate_sync_d::make(
                shape_a, shape_b,
                static_cast<vector_correlate_sync_d::CorrelateMode>(mode),
                normalize);
          },
          py::arg("input_shape_a"), py::arg("input_shape_b"),
          py::arg("mode") = CorrelateMode::FULL, py::arg("normalize") = false);

  py::class_<vector_correlate_sync_c, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_correlate_sync_c>>(
      m, "vector_correlate_sync_c")
      .def_static(
          "make",
          [](const gr::linalg::types::shape &shape_a,
             const gr::linalg::types::shape &shape_b,
             CorrelateMode mode = CorrelateMode::FULL, bool normalize = false) {
            return vector_correlate_sync_c::make(
                shape_a, shape_b,
                static_cast<vector_correlate_sync_c::CorrelateMode>(mode),
                normalize);
          },
          py::arg("input_shape_a"), py::arg("input_shape_b"),
          py::arg("mode") = CorrelateMode::FULL, py::arg("normalize") = false);

  py::class_<vector_correlate_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_correlate_sync_cd>>(
      m, "vector_correlate_sync_cd")
      .def_static(
          "make",
          [](const gr::linalg::types::shape &shape_a,
             const gr::linalg::types::shape &shape_b,
             CorrelateMode mode = CorrelateMode::FULL, bool normalize = false) {
            return vector_correlate_sync_cd::make(
                shape_a, shape_b,
                static_cast<vector_correlate_sync_cd::CorrelateMode>(mode),
                normalize);
          },
          py::arg("input_shape_a"), py::arg("input_shape_b"),
          py::arg("mode") = CorrelateMode::FULL, py::arg("normalize") = false);

  // Bind PDU blocks for all precision types
  using vector_correlate_pdu_f = gr::linalg::vector_correlate_pdu<float>;
  using vector_correlate_pdu_d = gr::linalg::vector_correlate_pdu<double>;
  using vector_correlate_pdu_c =
      gr::linalg::vector_correlate_pdu<std::complex<float>>;
  using vector_correlate_pdu_cd =
      gr::linalg::vector_correlate_pdu<std::complex<double>>;

  py::class_<vector_correlate_pdu_f, gr::basic_block,
             std::shared_ptr<vector_correlate_pdu_f>>(m,
                                                      "vector_correlate_pdu_f")
      .def_static(
          "make",
          [](const gr::linalg::types::vector_shapes &shapes,
             CorrelateMode mode = CorrelateMode::FULL, bool normalize = false) {
            return vector_correlate_pdu_f::make(
                shapes,
                static_cast<vector_correlate_pdu_f::CorrelateMode>(mode),
                normalize);
          },
          py::arg("input_shapes"), py::arg("mode") = CorrelateMode::FULL,
          py::arg("normalize") = false);

  py::class_<vector_correlate_pdu_d, gr::basic_block,
             std::shared_ptr<vector_correlate_pdu_d>>(m,
                                                      "vector_correlate_pdu_d")
      .def_static(
          "make",
          [](const gr::linalg::types::vector_shapes &shapes,
             CorrelateMode mode = CorrelateMode::FULL, bool normalize = false) {
            return vector_correlate_pdu_d::make(
                shapes,
                static_cast<vector_correlate_pdu_d::CorrelateMode>(mode),
                normalize);
          },
          py::arg("input_shapes"), py::arg("mode") = CorrelateMode::FULL,
          py::arg("normalize") = false);

  py::class_<vector_correlate_pdu_c, gr::basic_block,
             std::shared_ptr<vector_correlate_pdu_c>>(m,
                                                      "vector_correlate_pdu_c")
      .def_static(
          "make",
          [](const gr::linalg::types::vector_shapes &shapes,
             CorrelateMode mode = CorrelateMode::FULL, bool normalize = false) {
            return vector_correlate_pdu_c::make(
                shapes,
                static_cast<vector_correlate_pdu_c::CorrelateMode>(mode),
                normalize);
          },
          py::arg("input_shapes"), py::arg("mode") = CorrelateMode::FULL,
          py::arg("normalize") = false);

  py::class_<vector_correlate_pdu_cd, gr::basic_block,
             std::shared_ptr<vector_correlate_pdu_cd>>(
      m, "vector_correlate_pdu_cd")
      .def_static(
          "make",
          [](const gr::linalg::types::vector_shapes &shapes,
             CorrelateMode mode = CorrelateMode::FULL, bool normalize = false) {
            return vector_correlate_pdu_cd::make(
                shapes,
                static_cast<vector_correlate_pdu_cd::CorrelateMode>(mode),
                normalize);
          },
          py::arg("input_shapes"), py::arg("mode") = CorrelateMode::FULL,
          py::arg("normalize") = false);
}
