/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_product_outer.h) */
/* BINDTOOL_HEADER_FILE_HASH(c0bd497a39caddc0648e29bf0efa4f10) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/vector_product_outer.h>
// pydoc.h is automatically generated in the build directory
#include <vector_product_outer_pydoc.h>

void bind_vector_product_outer(py::module &m) {

  using vector_product_outer = gr::linalg::vector_product_outer;

  py::class_<vector_product_outer, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<vector_product_outer>>(m, "vector_product_outer",
                                                    D(vector_product_outer))

      .def(py::init(&vector_product_outer::make), D(vector_product_outer, make))

      ;
}
