/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_dot.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(120fee99e6a72ebd6b90d82791311c15) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/vector_dot.h>
// pydoc.h is automatically generated in the build directory
#include <vector_dot_pydoc.h>

void bind_vector_dot(py::module &m) {

  using vector_dot = gr::linalg::vector_dot;

  py::class_<vector_dot, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<vector_dot>>(m, "vector_dot_sync", D(vector_dot))

      .def(py::init(&vector_dot::make), py::arg("shape_a"), py::arg("shape_b"),
           D(vector_dot, make))

      ;
}
