/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_angle.h) */
/* BINDTOOL_HEADER_FILE_HASH(eca3099e0108e80cd12b3be709316589) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/vector_angle.h>

void bind_vector_angle(py::module &m) {

  using vector_angle_sync = gr::linalg::vector_angle_sync<float>;
  using vector_angle_sync_d = gr::linalg::vector_angle_sync<double>;
  using vector_angle_sync_cf =
      gr::linalg::vector_angle_sync<std::complex<float>>;
  using vector_angle_sync_cd =
      gr::linalg::vector_angle_sync<std::complex<double>>;

  py::class_<vector_angle_sync, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<vector_angle_sync>>(
      m, "vector_angle_sync_f", "Vector angle sync block for float")

      .def_static("make", &vector_angle_sync::make, py::arg("shape"),
                  py::arg("degrees") = false, "Create vector angle sync block");

  py::class_<vector_angle_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<vector_angle_sync_d>>(
      m, "vector_angle_sync_d", "Vector angle sync block for double")

      .def_static("make", &vector_angle_sync_d::make, py::arg("shape"),
                  py::arg("degrees") = false, "Create vector angle sync block");

  py::class_<vector_angle_sync_cf, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<vector_angle_sync_cf>>(
      m, "vector_angle_sync_cf", "Vector angle sync block for complex float")

      .def_static("make", &vector_angle_sync_cf::make, py::arg("shape"),
                  py::arg("degrees") = false, "Create vector angle sync block");

  py::class_<vector_angle_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<vector_angle_sync_cd>>(
      m, "vector_angle_sync_cd", "Vector angle sync block for complex double")

      .def_static("make", &vector_angle_sync_cd::make, py::arg("shape"),
                  py::arg("degrees") = false, "Create vector angle sync block");
}
