/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_to_matrix.h) */
/* BINDTOOL_HEADER_FILE_HASH(8a521de8cb54def5d19a5ca64cad5968) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/vector_to_matrix.h>
// pydoc.h is automatically generated in the build directory
#include <vector_to_matrix_pydoc.h>

void bind_vector_to_matrix(py::module &m) {

  // Bind sync blocks for all precision types
  using vector_to_matrix_sync_f = gr::linalg::vector_to_matrix_sync<float>;
  using vector_to_matrix_sync_d = gr::linalg::vector_to_matrix_sync<double>;
  using vector_to_matrix_sync_cf =
      gr::linalg::vector_to_matrix_sync<std::complex<float>>;
  using vector_to_matrix_sync_cd =
      gr::linalg::vector_to_matrix_sync<std::complex<double>>;

  py::class_<vector_to_matrix_sync_f, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_to_matrix_sync_f>>(
      m, "vector_to_matrix_sync_f")
      .def_static("make", &vector_to_matrix_sync_f::make,
                  py::arg("input_shape"), py::arg("output_shape"));

  py::class_<vector_to_matrix_sync_d, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_to_matrix_sync_d>>(
      m, "vector_to_matrix_sync_d")
      .def_static("make", &vector_to_matrix_sync_d::make,
                  py::arg("input_shape"), py::arg("output_shape"));

  py::class_<vector_to_matrix_sync_cf, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_to_matrix_sync_cf>>(
      m, "vector_to_matrix_sync_cf")
      .def_static("make", &vector_to_matrix_sync_cf::make,
                  py::arg("input_shape"), py::arg("output_shape"));

  py::class_<vector_to_matrix_sync_cd, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<vector_to_matrix_sync_cd>>(
      m, "vector_to_matrix_sync_cd")
      .def_static("make", &vector_to_matrix_sync_cd::make,
                  py::arg("input_shape"), py::arg("output_shape"));

  // Bind PDU blocks for all precision types
  using vector_to_matrix_pdu_f = gr::linalg::vector_to_matrix_pdu<float>;
  using vector_to_matrix_pdu_d = gr::linalg::vector_to_matrix_pdu<double>;
  using vector_to_matrix_pdu_cf =
      gr::linalg::vector_to_matrix_pdu<std::complex<float>>;
  using vector_to_matrix_pdu_cd =
      gr::linalg::vector_to_matrix_pdu<std::complex<double>>;

  py::class_<vector_to_matrix_pdu_f, gr::basic_block,
             std::shared_ptr<vector_to_matrix_pdu_f>>(m,
                                                      "vector_to_matrix_pdu_f")
      .def_static("make", &vector_to_matrix_pdu_f::make, py::arg("input_shape"),
                  py::arg("output_shape"));

  py::class_<vector_to_matrix_pdu_d, gr::basic_block,
             std::shared_ptr<vector_to_matrix_pdu_d>>(m,
                                                      "vector_to_matrix_pdu_d")
      .def_static("make", &vector_to_matrix_pdu_d::make, py::arg("input_shape"),
                  py::arg("output_shape"));

  py::class_<vector_to_matrix_pdu_cf, gr::basic_block,
             std::shared_ptr<vector_to_matrix_pdu_cf>>(
      m, "vector_to_matrix_pdu_cf")
      .def_static("make", &vector_to_matrix_pdu_cf::make,
                  py::arg("input_shape"), py::arg("output_shape"));

  py::class_<vector_to_matrix_pdu_cd, gr::basic_block,
             std::shared_ptr<vector_to_matrix_pdu_cd>>(
      m, "vector_to_matrix_pdu_cd")
      .def_static("make", &vector_to_matrix_pdu_cd::make,
                  py::arg("input_shape"), py::arg("output_shape"));
}
