/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(vector_Kronecker.h) */
/* BINDTOOL_HEADER_FILE_HASH(f63936ed889442a80880526e5dd88e13) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/vector_Kronecker.h>
// pydoc.h is automatically generated in the build directory
#include <vector_Kronecker_pydoc.h>

void bind_vector_Kronecker(py::module &m) {

  using vector_Kronecker = gr::linalg::vector_Kronecker;

  py::class_<vector_Kronecker, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<vector_Kronecker>>(m, "vector_Kronecker",
                                                D(vector_Kronecker))

      .def(py::init(&vector_Kronecker::make), D(vector_Kronecker, make))

      ;
}
