/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(zeros.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c8184134739ac267292fca30bc8f4477) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/linalg/zeros.h>
// pydoc.h is automatically generated in the build directory
#include <zeros_pydoc.h>

void bind_zeros(py::module &m) {

  using zeros_sync_f = gr::linalg::zeros<float>;
  using zeros_sync_d = gr::linalg::zeros<double>;
  using zeros_sync_cf = gr::linalg::zeros<std::complex<float>>;
  using zeros_sync_cd = gr::linalg::zeros<std::complex<double>>;

  py::class_<zeros_sync_f, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<zeros_sync_f>>(m, "zeros_sync_f", D(zeros))

      .def(py::init(&zeros_sync_f::make), py::arg("shape"), D(zeros, make))
      .def_static("make", &zeros_sync_f::make, py::arg("shape"),
                  D(zeros, make));

  py::class_<zeros_sync_d, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<zeros_sync_d>>(m, "zeros_sync_d", D(zeros))

      .def(py::init(&zeros_sync_d::make), py::arg("shape"), D(zeros, make))
      .def_static("make", &zeros_sync_d::make, py::arg("shape"),
                  D(zeros, make));

  py::class_<zeros_sync_cf, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<zeros_sync_cf>>(m, "zeros_sync_cf", D(zeros))

      .def(py::init(&zeros_sync_cf::make), py::arg("shape"), D(zeros, make))
      .def_static("make", &zeros_sync_cf::make, py::arg("shape"),
                  D(zeros, make));

  py::class_<zeros_sync_cd, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<zeros_sync_cd>>(m, "zeros_sync_cd", D(zeros))

      .def(py::init(&zeros_sync_cd::make), py::arg("shape"), D(zeros, make))
      .def_static("make", &zeros_sync_cd::make, py::arg("shape"),
                  D(zeros, make));
}
